README.md

mcp-rs-template is a MCP CLI server project template for Rust

chore: add mcp-rs-template

---

README.md

This MCP server implementation is quite powerful, it allows a Customer Data Platform, Apache Unomi, to act as the memory of a GPT chat. See README for more details.

Add the MCP Server implementation to access Apache Unomi profiles

---

README.md

This PR adds a link to a MCP BigQuery Server. The server is maintained in its own repository at https://github.com/ergut/mcp-bigquery-server and is available via npm.

Update README.md by adding BigQuery MCP server

---

README.md

Add godoc-mcp server to the list
This PR adds godoc-mcp, a specialized MCP server designed to make Go development with AI assistants more efficient and effective. Unlike traditional file-based approaches that require processing entire source files, godoc-mcp provides AI models with direct, token-efficient access to package symbols and/or source.
The server is particularly valuable for the MCP ecosystem as it demonstrates how specialized documentation servers can dramatically improve AI-assisted development by eliminating full file reads and providing structured, efficient access to context-specific documentation.

Add godoc-mcp server to Other Tools and Integrations section

---

README.md

Adding two new servers:
- simple-timeserver - server to allow checking both local machine time and UTC time from an NTP server
- simple-openai-assistant - server enabling use of OpenAI's assistants

Adding new servers - simple-timeserver and simple-openai-assistant

---

README.md

Adding mcp-golang, a framework for building golang mcp servers, focussing on type safety.

Add mcp-golang

---

README.md

mcp-client-cli is yet another CLI Python program that implement MCP client protocol

Add mcp-client-cli

---

README.md

We built an MCP server - https://github.com/metoro-io/metoro-mcp-server - for Metoro which allows MCP clients to directly query the status of their Kubernetes clusters and all workloads running inside using natural language.

Add the Metoro MCP server

---

README.md

The current list of community servers has lots of data sources but seems to be missing any sort of data visualization tools. While Claude Desktop natively renders Recharts visualizations well, it would be beneficial to have a way to produce charts in a canonical MCP-like way (especially for alternative clients). `mcp-vegalite-server` meets this requirement.

Added isaacwasserman/mcp-vegalite-server

---

README.md

This PR adds three new MCP server implementations:
- imessage-query-fastmcp-mcp-server: A Python-based MCP server that provides secure access to iMessage databases on macOS. Features include:
- Safe, validated phone number handling
- Proper attachment management
- Built with FastMCP framework
- sqlite-explorer-fastmcp-mcp-server: A Python-based MCP server for exploring SQLite databases with:
- Read-only access for safety
- Built-in query validation
- FastMCP framework integration
- mcp-ragdocs: A Python-based MCP server that enhances AI capabilities with:
- Documentation retrieval through vector search
- Context augmentation for AI responses
- Efficient documentation processing

Add three new MCP servers for iMessage, SQLite, and Documentation RAG

---

README.md

Integration was previously labeled as `@modelcontextprotocol/server-langchain`, which does not exist. The correct identifier is `rectalogic/langchain-mcp` (which is an MCP client, not a server).

Fixed name of rectalogic/langchain-mcp

---

README.md

Access global time data
This is useful if you have friends in different countries and you need to get the delta time.
Lets the LLM query the users current time, which is useful for general purpose agent stuff.
Uses the local system clock so that needs to be accurate.

Add SecretiveShell/MCP-timeserver

---

README.md

Added a new "Art & Culture" category (🎨) to organize MCP servers related to cultural institutions and artistic content. The Rijksmuseum MCP server is added as the first entry in this category, providing integration with the Rijksmuseum API for artwork search, details, and collections.
- Added new "Art & Culture" category with descriptive introduction
- Added category to the navigation list with 🎨 emoji
- Added Rijksmuseum MCP server as first entry
This addition helps organize cultural/artistic integrations and sets the foundation for similar servers in the future.

feat: add Art & Culture category with Rijksmuseum MCP server

---

README.md

> This MCP server provides a tool to download entire websites using wget. It preserves the website structure and converts links to work locally.
https://github.com/pskill9/website-downloader
The server provides a tool called `download_website` with the following parameters:
- `url` (required): The URL of the website to download
- `outputPath` (optional): The directory where the website should be downloaded. Defaults to the current directory.
- `depth` (optional): Maximum depth level for recursive downloading. Defaults to infinite. Set to 0 for just the specified page, 1 for direct links, etc.
```json
{
"url": "https://example.com",
"outputPath": "/path/to/output",
"depth": 2  // Optional: Download up to 2 levels deep
}
```
The website downloader:
- Downloads recursively with infinite …

feat: Added new website-downloader mcp server

---

README-ja.md
README-zh.md
README.md

mcp-difyworkflow-server is an mcp server Tools application that implements the query and invocation of Dify workflows, supporting the on-demand operation of multiple custom Dify workflows.

add mcp-difyworkflow-server

---

README.md

> A Model Context Protocol (MCP) server that provides tools for fetching stories from Hacker News. This server parses the HTML content from news.ycombinator.com and provides structured data for different types of stories (top, new, ask, show, jobs).
- Fetch different types of stories (top, new, ask, show, jobs)
- Get structured data including titles, URLs, points, authors, timestamps, and comment counts
- Configurable limit on number of stories returned
- Clean error handling and validation

chore: Added MCP server for hacker news

---

README.md

Added a new MCP server that has the following features for interacting with hackernews:
```
get_stories Fetching (top, new, ask_hn, show_hn) stories
get_story_info Fetching comments associated with a story
search_stories Searching for stories by query
get_user_info Fetching user info
```

Added MCP Server for Hackernews

---

README-ja.md
README-zh.md
README.md

A Model Context Protocol (MCP) server implementation that provides Elasticsearch interaction.
https://github.com/cr7258/elasticsearch-mcp-server

add elasticsearch-mcp-server

---

README-ja.md
README-zh.md
README.md

This PR adds iterm-mcp which provides iTerm access to the MCP client. You can interact with the terminal and ask questions about the display contents.
https://github.com/ferrislucas/iterm-mcp

Add iterm-mcp

---

README.md

Add r-huijts/xcode-mcp-server with TypeScript, local service, and macOS support indicators. The server provides Xcode IDE integration for project management, file operations, and build automation.

feat(readme): add Xcode MCP Server to Developer Tools section

---

README.md

Add an entry for [mcp-server-ipinfo](https://github.com/briandconnelly/mcp-server-ipinfo) to the _Location Services_ section.
This server uses the [IPInfo](https://ipinfo.io) API to retrieve information about the user's geographic location and network information via their IP address.

Add mcp-server-ipinfo

---

README.md

A Model Context Protocol (MCP) server that enables AI models to interact with Nostr, allowing them to post notes and interact with the freedom of speech protocol.
```bash
npm run dev
npm start
```
Posts a new note to the Nostr network.
Example input:
```json
{
"content": "Hello from Nostr! 👋"
}
```

add: nostr-mcp a Nostr MCP Server

---

README.md

Add Asana MCP server to the "Other Tools and Integrations" section
This PR adds the TypeScript-based MCP server for Asana that allows Claude and other MCP clients to interact with the Asana API.
I've followed the existing format within the section, including the appropriate icons for TypeScript (📇) and Cloud Service (☁️).

Add Asana MCP server

---

README.md

Adds "[Claude Debugs For You](https://github.com/jasonjmcghee/claude-debugs-for-you)", which (though originally built with Claude Desktop in mind) enables a given MCP client to use the debugger in VS Code, which means the LLM can set breakpoints, continue execution, evaluate expressions in-context along with finding and reading files, if required.
It's language agnostic - the burden is on the developer to be using the proper `launch.json` to enable debugging (in general).
LLMs seem to be able to solve problems much better if they can directly inspect values in code during execution (go figure), so it's valuable as an MCP Server.
Here's an example of it being used alongside Continue.
https://github.com/user-attachments/assets/fc4a55dc-2f09-4a7d-8518-b1c360d49bbc

Add the automated debugger: "Claude Debugs For You"

---

README.md

This PR adds the Base MCP server (@base/base-mcp) to the Finance & Fintech section. 
The server provides:
- Base Network integration for onchain tools
- Interaction with Base Network and Coinbase API
- Wallet management and fund transfers
- Smart contract deployment and interaction
- DeFi operations
The entry follows the contribution guidelines:
- Added in alphabetical order within the Finance & Fintech section
- Includes appropriate emoji indicators (🎖️ for official implementation, 📇 for TypeScript, ☁️ for Cloud Service)
- Provides a clear and concise description
- Maintains consistent formatting

Add Base MCP server

---

README.md

Since the MCP server is within our OSS monorepo, I made the primary link to a post explaining how to use Convex's MCP server and then added a link to the source code in a second link. Let me know if that works!
Should I also add this entry to the Chinese and Japanese readmes too? I don't know either of those languages but can put up a first pass with machine translation.

Add Convex MCP server

---

README.md

This PR adds information about tfmcp, a command-line tool that enables LLMs to manage and operate Terraform environments through the Model Context Protocol (MCP).
- Added tfmcp to the Cloud Platforms section
- Included key features and capabilities
- Provided installation instructions and basic usage examples
- Referenced the GitHub repository and latest release information
tfmcp is an experimental command-line tool that allows AI assistants like Claude to interact with Terraform via the Model Context Protocol. It enables reading configuration files, analyzing plan outputs, applying configurations, managing state, and creating or modifying Terraform infrastructure as code.
- GitHub repository: https://github.com/nwiizo/tfmcp
- blog post: …

Add Terraform MCP server (tfmcp) to Cloud Platforms section

---

README.md

`KS-GEN-AI/jira-mcp-server` and `KS-GEN-AI/confluence-mcp-server` have mixed up descriptions. Updating with correct descriptions.

fix: swap the description for jira-mcp-server and confluence-mcp-server

---

README-ja.md
README-zh.md
README.md

This PR adds the National Park Service API MCP server to the Travel & Transportation category in all three language versions of the README (English, Chinese, and Japanese).
- Added entry for `KyrieTangSheng/mcp-server-nationalparks` to the Travel & Transportation section in:
- README.md (English)
- README-zh.md (Chinese)
- README-ja.md (Japanese)
This MCP server provides integration with the National Park Service API, allowing AI assistants to access information about U.S. National Parks including park details, alerts, visitor centers, campgrounds, and events. It helps users plan trips to national parks and get up-to-date information about park conditions and activities.
Thank you for maintaining this valuable resource for the MCP community!

Add National Parks MCP Server to Travel & Transportation Category

---

README.md

This PR adds the AWS MCP Server to the Cloud Platforms section. This server enables AI assistants to execute AWS CLI commands, use Unix pipes, and apply prompt templates for common AWS tasks, all within a secure Docker environment with multi-architecture support (AMD64/ARM64).
- Added AWS MCP Server in alphabetical order within the Cloud Platforms section
- Included appropriate icons (Python, Cloud Service)
- Provided a concise description highlighting the key capabilities
The AWS MCP Server is an open-source project that extends AI assistants' capabilities to interact with AWS infrastructure in a secure and controlled manner.

Add AWS MCP Server to Cloud Platforms section

---

README.md

Add mcp-chat as utility
Hi, I wrote [mcp-chat](https://github.com/Flux159/mcp-chat) in order to quickly test & iterate with prompts for my kubernetes mcp server. Thought the utility would be helpful for other MCP server developers so decided to add it here

Add mcp-chat as utility

---

README.md

I noticed the Gaming section was a bit lonely, so I'd like to add my Godot MCP server that I've been developing for a couple of weeks.
This server provides comprehensive Godot engine integration, allowing:
- Launching the Godot editor for specific projects
- Running and debugging Godot projects
- Creating and managing scenes programmatically
- Adding nodes with customizable properties
- Loading sprites and textures
- Exporting 3D scenes as MeshLibrary resources
- UID management for Godot 4.4+
Thanks!

add godot-mcp server

---

README-zh.md
README.md

Hi,
now I have write scala mcp framwork ,shade from modelcontextprotocol.io .
--1. Enterprise-grade high-throughput performance and high-throughput capabilities.
--2. Support for the Spring AI framework.
--3. Support for asynchronous, multi-threaded invocations.
--4. Multi-tenant support, with local PyTorch model deployment and invocation,
--5. Support integration with big data frameworks like Spark and Flink.

add scala mcp framwork to list

---

README-ja.md
README-zh.md
README.md

[AniList MCP](https://github.com/yuna0x0/anilist-mcp) is a Model Context Protocol (MCP) server that interfaces with the AniList API, allowing LLM clients to access and interact with anime, manga, character, staff, and user data from AniList.

Add AniList MCP for anime and manga information

---

README.md

This PR adds the FirstCycling MCP server (https://github.com/r-huijts/firstcycling-mcp) to the awesome-mcp-servers list.
Changes made:
- Added a new "🏃 Sports" category to organize sports-related MCP servers
- Added FirstCycling MCP server with description of its key features
The FirstCycling MCP server provides natural language access to cycling race data, results, and statistics from FirstCycling.info. It's a valuable addition to the list as it demonstrates how MCP can be used to make sports data more accessible through natural language interfaces.

docs: add Sports category with FirstCycling MCP server

---

README.md

I added the [Memgraph MCP Server](https://github.com/memgraph/mcp-memgraph) to the Databases list. Wasn't sure where to put it since it isn't ordered, so let me know if this needs to be changed.

Add Memgraph MCP Server

---

README.md

This PR adds a new entry for the GitHub Enterprise MCP server to the list. 
The server integrates with the GitHub Enterprise Server API for seamless repository, issues, PR, and workflow management. 
Thank you for curating this awesome collection!
repository: https://github.com/ddukbg/github-enterprise-mcp

Add GitHub Enterprise(GHES) MCP Server Entry

---

README.md

Safe Local Python Executor
An MCP server (stdio transport) that wraps Hugging Face's [LocalPythonExecutor](https://github.com/huggingface/smolagents/blob/main/src/smolagents/local_python_executor.py) (from the [smolagents](https://huggingface.co/docs/smolagents/en/index) framework). It is a custom Python runtime that provides basic isolation/security when running Python code generated by LLMs locally. It does not require Docker or VM. This package allows to expose the Python executor via MCP (Model Context Protocol) as a tool for LLM apps like Claude Desktop, Cursor or any other MCP compatible client. In case of Claude Desktop this tool is an easy way to add a missing Code Interpreter (available as a plugin in ChatGPT for quite a while already). …

Adding local Python interpreter that is safe

---

README.md

Add browser-control-mcp, which is An MCP server paired with a browser extension that enables LLM clients to control the user's browser (Firefox).

Add browser-control-mcp server

---

README.md

Adding Deep Research MCP server to the community MCP server list.
Youtube：https://youtu.be/_a7sfo5yxoI
Github：https://github.com/reading-plus-ai/mcp-server-deep-research

Adding Deep Research MCP server

---

README-ja.md
README-zh.md
README.md

This PR adds [ios-simulator-mcp](https://github.com/joshuayoes/ios-simulator-mcp) to the Developer Tools section. 
[ios-simulator-mcp](https://github.com/joshuayoes/ios-simulator-mcp) is a MCP server for interacting with iOS simulators. This server allows you to interact with iOS simulators by getting information about them, controlling UI interactions, and inspecting UI elements.
It appears similar to [simulator-mcp-server](https://github.com/JoshuaRileyDev/simulator-mcp-server) but it is more focused on UI input automation than managing server instances or app installs.

Add ios-simulator-mcp

---

README.md

This PR adds [Template MCP Server](https://github.com/mcpdotdirect/template-mcp-server) to the Frameworks section of the README.
Template MCP Server is a CLI tool to create new Model Context Protocol server projects with TypeScript support, dual transport options, and an extensible structure.
It allows anyone to run :
`npx npx @mcpdotdirect/create-mcp-server`
and a new a new MCP server project will be setup in the current directory.
- Added Template MCP Server to the "For servers" subsection in the Frameworks section

Add Template MCP Server to Frameworks section

---

README-ja.md
README-zh.md
README.md

Adds a new MCP server to all README files for Ghidra reverse engineering under Security.
[README.md](https://github.com/punkpeye/awesome-mcp-servers/compare/main...13bm:awesome-mcp-servers:main?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) - Added English 13bm/GhidraMCP to the list of MCP server projects.
[README.md](https://github.com/punkpeye/awesome-mcp-servers/compare/main...13bm:awesome-mcp-servers:main?expand=1#diff-6323ab8bbdb204fef907b113c1c602229d4baef7abcd9c499aba1dd23bfe531c) - Added Japanese 13bm/GhidraMCP to the list of MCP server projects.
[README.md](https://github.com/punkpeye/awesome-mcp-servers/compare/main...13bm:awesome-mcp-servers:main?expand=1#diff-2b8d2db04fe3277c3a06cbdf5da2ba7659f95e19e31f59d5382b40ac81a1a98d) - Added Mandarin …

Adds a new MCP server to all README files for Ghidra reverse engineering under Security.

---

README.md

Add a link to a SonarQube MCP server.
Allows one to list projects and issues on those projects.

Add sonarqube-mcp-server

---

README.md

This PR adds the [Starknet MCP Server](https://github.com/mcpdotdirect/starknet-mcp-server) to the Finance & Fintech section.
The server provides a comprehensive toolkit for interacting with the Starknet blockchain ecosystem, enabling AI agents to:
- Query account balances for ETH and STRK tokens
- Interact with smart contracts (read and write)
- Resolve human-readable StarknetIDs to addresses
- Manage NFT tokens and collections
- Check transaction status and block information
- Perform token transfers
The entry has been added in alphabetical order with appropriate emoji tags (📇 ☁️).

Add Starknet MCP server to README

---

README.md

This pull request includes an update to the `README.md` file, adding a new repository to the list of projects.
Projects update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R485): Added the `gabfr/waha-api-mcp-server` repository, which is an MCP server with openAPI specs for using the WhatsApp unofficial API.

chore: add github.com/gabfr/waha-api-mcp-server

---

README.md

Jupyter Notebook MCP  connects Jupyter Notebook to Claude AI, allowing Claude to directly interact with and control Jupyter Notebooks. This integration enables AI-assisted code execution, data analysis, visualization, and more.

docs: Add Jupyter Notebook MCP to README.

---

README.md

This PR introduces a new **"Support & Service Management"** category to categorize tools related to customer support, IT service management, and helpdesk operations.  
- **Added category:** `🎧 Support & Service Management`  
- **Added tool:** Freshdesk MCP  
- **Features:**  
- Automates ticket handling  
- Retrieves customer data  
This addition helps organise CRM and ITSM-related tools and prepares for future integrations like Freshservice,ServiceNow and so on.  
Let me know if any modifications are needed! 🚀

📦 feat: Add Support & Service Management category with Freshdesk integration

---

README-ja.md
README.md

This pull request includes updates to the `README` files in both Japanese and English to add a new MCP server integration for Google Calendar.
Updates to `README` files:
* [`README-ja.md`](diffhunk://#diff-6323ab8bbdb204fef907b113c1c602229d4baef7abcd9c499aba1dd23bfe531cR100): Added a new entry for `google-calendar-mcp`, an MCP server for integrating with the Google Calendar API, supporting creation, updating, retrieval, and deletion of Google Calendar events, and based on TypeScript.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R192): Added a new entry for `google-calendar-mcp`, an MCP server for interfacing with the Google Calendar API, based on TypeScript.

Add new server [google-calendar-mcp]

---

README-zh.md
README.md

A Model Context Protocol (MCP) server for querying the [CVE-Search](https://www.cve-search.org/api/) API. This server provides comprehensive access to CVE-Search, browse vendor and product、get CVE per CVE-ID、get the last updated CVEs.

Add CVE-Search MCP Server

---

README.md

This PR adds the pluggedin-mcp-proxy to the Aggregators section. Plugged.in MCP Server acts as a proxy server that combines multiple MCP servers into a single unified interface with extensive visibility features. It fetches tool, prompt, and resource configurations from the plugged.in App and intelligently routes requests to the appropriate underlying MCP servers.
- Universal MCP Compatibility with any MCP client (Claude, Cline, Cursor, etc.)
- Multi-Server Support for both STDIO and WebSocket MCP servers
- Namespace Isolation to keep joined MCPs separate and organized
- Multi-Workspace Layer to switch between different sets of MCP configurations
- Extensive visibility of prompts, resources, and templates across all connected servers
- Discovery functionality to see details of available …

add: pluggedin-mcp-proxy to Aggregators section

---

README.md

Adding the Alpaca Trading MCP Server to the collection.
This PR adds the Alpaca Trading MCP Server, which provides an interface to the Alpaca trading API. It allows users to manage their stock and crypto portfolios, place trades, and access market data through MCP.
**Key features:**
- Account Management: View account details, balances, and portfolio status
- Trading: Place market, limit, stop, and stop-limit orders
- Portfolio Management: View positions, calculate performance, and close positions
- Market Data: Access real-time quotes and historical price data
- Asset Information: Get details about tradable assets
This server provides resources for account information, positions, orders, market quotes, and asset information, as well as tools for placing and managing orders using the …

Add new alpaca-mcp server

---

README.md

Added an entry for [MarkItDown](https://github.com/microsoft/markitdown), which is a tool for converting many file formats to Markdown for LLM consumption.
MarkItDown has nearly 42,000 stars on GitHub, and is the core of the FileSurfer agent in AutoGen's [Magentic-One](https://www.microsoft.com/en-us/research/articles/magentic-one-a-generalist-multi-agent-system-for-solving-complex-tasks)
This is the official MCP server, written by me -- the primary maintainer of MarkItDown, and the first author on Magentic-One.

Added an entry for MarkItDown MCP server.

---

README.md

Add [mcp-browser-kit](https://github.com/ndthanhdev/mcp-browser-kit), an MCP server for interacting with manifest v2 compatible browsers.

Add mcp-browser-kit

---

README.md

>A Model Context Protocol (MCP) server that implements the Zettelkasten knowledge management methodology, allowing you to create, link, and search atomic notes through Claude and other MCP-compatible clients.
https://github.com/entanglr/zettelkasten-mcp

Add `entanglr/zettelkasten-mcp`

---

README.md

An MCP server that hooks up to the Kagi API to provide access to Kagi Search and to the Universal Summarizer.

Add official Kagi Search MCP server

---

README.md

This tool is fairly popular with 1.5k stars.  I've been using it 10 days.  It has around 20 MCP tools for controlling your local machine (eg. edit_block, move_file, search_code kill_process and execute_command).
I don't understand how to use the Category icons when something can be used for the Command line, Search, Filesystems, and developing, so this only has filesystem, scope & OS icons.

Add desktop commander mcp

---

README.md

Added jwaxman19/qlik-mcp to the Data Platforms section. This MCP server enables interaction with Qlik Cloud API for querying applications, sheets, and extracting data from visualizations.

Add Qlik Cloud MCP server to Data Platforms section

---

README-zh.md
README.md

A Go-based MCP connector for Jira that enables AI assistants like Claude to interact with Atlassian Jira. This tool provides a seamless interface for AI models to perform common Jira operations including issue management, sprint planning, and workflow transitions.

Add new Jira server

---

README.md

[the0807/GeekNews-MCP-Server](https://github.com/the0807/GeekNews-MCP-Server) 🐍 ☁️ - An MCP Server that retrieves and processes news data from the GeekNews site.

add GeekNews MCP Server

---

README-ja.md
README-ko.md
README-zh.md
README-zh_TW.md
README.md

I went in to add the [mcp-flowcore-platform](https://github.com/flowcore-io/mcp-flowcore-platform) to the Data Platform sections. 
However, when went to add it to the other readme files, I noticed that the *Data Platforms* section was missing, so I added them. Hope that is ok :)

Added missing group to other languages, and Flowcore MCP Platform

---

README.md

I added one line to the README to include arxiv-latex-mcp, an MCP that retrieves the LaTeX source of arXiv papers for handling mathematical content and equations.

add arxiv-latex-mcp

---

README.md

This PR adds the [balldontlie-mcp](https://github.com/mikechao/balldontlie-mcp) to the list of community servers in the Sports section.
The balldontlie-mcp leverages the [balldontlie api](https://www.balldontlie.io/) to provide information about players, teams and games for the NBA, MLB and NFL.
- **get_teams**
- Get a list of teams for the NBA, NFL or MLB
- Inputs:
- `league` (enum ['NBA', 'NFL', 'MLB']): The sports league to get teams for
- **get_players**
- Gets a list of players for the NBA, NFL or MLB
- Inputs:
- `league` (enum ['NBA', 'NFL', 'MLB']): The sports league to get players for
- `firstName` (string, optional): The first name of the player to search for
- `lastName` (string, optional): The last name of the player to search for
- `cursor` (number, optional): Cursor for …

Added balldontlie-mcp

---

README.md

Due to project requirement, we need change beeper mcp into https://github.com/intentos-labs/beeper-mcp.
Previous repo(https://github.com/unibaseio/beeper-mcp) is archived and will be deleted when this commit is merged.
Previous commit: https://github.com/punkpeye/awesome-mcp-servers/pull/487

fix(README): change beeper mcp git url

---

README.md

Add new MCP Server into tools & integrations - Miro SDK wrapper. Available on npm.

Add new Miro MCP Server

---

README.md

Other servers don't give back a full week or only give a single forecast for each day instead of broken down by time of day.

Add weekly weather MCP server with full 7-day forecasted data

---

README.md

Using ffmpeg command line to achieve an mcp server, can be very convenient, through the dialogue to achieve the local video search, tailoring, stitching, playback and other functions
The server implements the following tools: <br/>
- `find_video_path`
The parameters are directory and file name, file name can be complete, or is not suffixed, recursive search in the directory, return the full path
- `clip_video`
The parameter is the file path, start time, end time or duration, and returns the trimmed file path
- `concat_videos`
The parameters are the list of files, the output path, and if the video elements in the list of files, such as width, height, frame rate, etc., are consistent, quick mode synthesis is automatically used
<br/>
More features are coming
1. Download project
```
git clone …
```

Add new ffmpeg-mcp server

---

README.md

This pull request adds the Atlassian MCP server to the collection, which provides integration capabilities with Atlassian products (Jira and Confluence).
Key features added:
- Jira integration for issue tracking, project management, and agile workflows
- Confluence integration for documentation and knowledge management
- Support for common Atlassian operations like searching, creating, and updating content
- Comprehensive API coverage for both Jira and Confluence functionalities
The server has been added following the repository's guidelines:
- Maintained alphabetical ordering within its category
- Included clear description of functionality
- Followed existing formatting and style
- Added appropriate links to the repository
This addition will help users integrate Atlassian tools into …

Add Atlassian MCP Server for Jira and Confluence Integration

---

README.md

I updated the README file to include a new third-party MCP server named slack-mcp-server, which supports communicating with Slack Workspaces on advanced level.
Motivation and Context
Unlike the "reference server" version of the Slack MCP, proposed MCP server supports stdio and sse transports, proxy settings and in my opinion, most important it does not require bot/apps being created in the Slack Workspace that will require approvals so it is possible to setup MCP server fully for yourself on behalf your own account.

docs: Update README.md to add a new Slack MCP

---

README.md

Added JDBC (Open Database Connectivity) MCP Servers to the Reference Servers list.
JDBC MCP Server that provide generic data connectivity using existing JDBC Drivers (Connectors) provided by any DBMS. These connectors work with any JDBC Driver.
- Server: database management system (dbms)
- Changes to: resources 
A Generic MCP Server that connects to JDBC-accessible databases is a powerful showcase of the practical utility of MCP. Fundamentally, this improves the context of any LLM-based MCP client by providing rich context from database management systems -- in generic, rather than DBMS-specific, manner. 
This MCP server has been developed by JDBC experts knowledgeable in both the usage and driver implementation aspects of the data access protocol.
* Claude Desktop
* Cline extension to …

MCP Server for JDBC

---

README.md

The Grafana MCP server was rewritten from Python to Go a bit ago. This just updates the documentation to match the rewrite.

Change mcp-grafana from Python to Go

---

README.md

Add the following servers to README.md:
- chainlink-feeds-mcp: providing real-time access to Chainlink's decentralized on-chain price feeds.
- cointelegraph-mcp:  providing real-time access to the latest news from Cointelegraph.
- crypto-trending-mcp: tracking the latest trending tokens on CoinGecko.
- crypto-whitepapers-mcp: serving as a structured knowledge base of crypto whitepapers.
- defi-yields-mcp: enabling agents to explore DeFi yields opportunities.
- twitter-username-changes-mcp: tracking the historical changes of Twitter usernames.

Add 6 crypto-related MCP servers.

---

README.md

I've added the Jotdown MCP server to the repository. This server gives LLMs the ability to:
* 📝 Create and update Notion pages.
* 📚 Generate mdbook-style documentation with structured chapters.
The server is implemented in Rust (🦀) and is self-hostable (🏠).
Repository link: [https://github.com/Harry-027/JotDown](https://github.com/Harry-027/JotDown)

Add Jotdown MCP server

---

README.md

Adds `gin-mcp` to the list of MCP tools/libraries.
**[gin-mcp](https://github.com/ckanthony/gin-mcp)** is a Go library that provides a zero-configuration bridge to automatically expose existing Gin web framework APIs as MCP tools. It helps developers connect their backend services to MCP clients like Cursor with minimal effort.
Key features:
- Automatic route discovery and basic schema inference.
- Mounts directly onto an existing `gin.Engine`.
- Option to register custom schemas and filter exposed endpoints.

Add gin-mcp (Go Gin Framework Bridge)

---

README.md

This PR adds the 8enSmith/mcp-open-library MCP server.
Details:
- Server: [8enSmith/mcp-open-library](https://github.com/8enSmith/mcp-open-library)
- Details: A Model Context Protocol (MCP) server for the Open Library API that enables AI assistants to search for book information
- Category: Art & Culture

Add new mcp-open-library server

---

README-ja.md
README.md

[modelcontextprotocol/servers](https://github.com/modelcontextprotocol/servers)
this mcp is much more powerful and also referred in the official one

add Powerfull kibela

---

README.md

I am adding [TickTick](https://ticktick.com) MCP server to the list -- TickTick is a todo list app for managing project tasks and notes.

Add TickTick MCP server

---

README.md

Official MCP server for [dbt (data build tool)](https://www.getdbt.com/product/what-is-dbt) providing integration with dbt Core/Cloud CLI, project metadata discovery, model information, and semantic layer querying capabilities.
LinkedIn post by Jason Ganz, DX at dbt Labs: https://www.linkedin.com/posts/activity-7320119837190492160-r_TV
Blog Post with examples: https://docs.getdbt.com/blog/introducing-dbt-mcp-server

add dbt Labs official MCP server: dbt-mcp

---

README.md

Anthropic has handed development of the [GitHub MCP server](https://github.com/github/github-mcp-server) over to GitHub. We have placed a [deprecation notice](https://github.com/modelcontextprotocol/servers/tree/main/src/github#github-mcp-server) on the old repo to redirect to the official server. This PR adds the official server and removes the deprecated server.

add official github server and remove deprecated version

---

README.md

Add new Webhook Tester MCP server under Developer Tools.
A FastMCP server for interacting with webhook-test.com, designed to automate and manage Webhook URLs. It enables users to create, retrieve, and delete webhooks. Tested with demo using Claude.

Add new Webhook Tester MCP server under Developer Tools

---

README.md

This PR adds my MCP server implementation [geoserver-mcp](https://github.com/mahdin75/geoserver-mcp) to the Location section. It connects LLMs to the GeoServer REST API, allowing AI assistants to interact with geospatial data and services.

Add geoserver-mcp to Location section

---

README.md

The server looks up a single or a group of domain names and reports if they are `registered` or `available`.
First via RDAP and if RDAP isn't available (since WHOIS is officially being deprecated, but not all the NICs migrated to RDAP), then fall back to WHOIS.

Added link to domain-lookup-mcp server

---

README.md

Adds https://github.com/hydrolix/mcp-hydrolix. Unfortunately, I only speak English and will need some help with the localization for the other READMEs.
See also https://glama.ai/mcp/servers/@hydrolix/mcp-hydrolix

Add official Hydrolix MCP server

---

README.md

Add the Couchbase MCP server that allows MCP clients to access & analyze the data stored in their Couchbase clusters (both self-managed & Capella)

Add Couchbase MCP server to the Database MCP servers section

---

README.md

mcp-log-proxy can be used to see the messages to and from a MCP client and a MCP server using a Web interface.

add mcp-log-proxy server

---

README.md

Add gnuradioMCP server - an MCP server for GNU Radio that enables LLMs to autonomously create and modify RF `.grc` flowcharts.

Add gnuradioMCP server

---

README.md

- crypto-rss-mcp: Aggregating real-time cryptocurrency news from multiple RSS feeds.
- modbus-mcp: An MCP server that standardizes and contextualizes industrial Modbus data.
- opcua-mcp: Connecting to OPC UA-enabled industrial systems.

Add 3 MCP servers

---

README.md

mcp-graphql-forge lets you turn any GraphQL endpoint into an MCP server whose tools are defined in YAML files that specify the GraphQL queries and their parameters. This allows you to create a modular, secure, and minimal server that can be easily extended without modifying the application code.

Add new UnitVectorY-Labs/mcp-graphql-forge server

---

README.md

Add ssh-mcp server to README.md for SSH control of Linux and Windows servers via Model Context Protocol.

Add ssh-mcp server

---

README.md

Netdata added an MCP server allowing LLMs to use the full set of observability data for exploration and root cause analysis.

Add Netdata to README.md

---

README-zh.md
README-zh_TW.md
README.md

Add Wenyan MCP Server, which lets AI automatically format Markdown articles and publish them to WeChat GZH.

Add Wenyan MCP

---

README.md

Adding an MLB MCP server I wrote in Python that wraps the official MLB API.

Add MLB MCP server to README

---

README.md

Adds Biel.ai [MCP server](https://docs.biel.ai/integrations/mcp-server).

Add Biel.ai MCP server

---

README.md

meta-ads-mcp is now under pipeboard-co

Update meta-ads-mcp's org

---

README.md

Adding CipherTrust Manager MCP server to Security section. Provides secure key management, cryptographic operations, and compliance monitoring through AI assistants.

Add CipherTrust Manager MCP server

---

README.md

An MCP to give your chat agent a better understanding of your application's architecture in the context of the current chat. Based on Aider's Repo Map functionality.
[Github Repo](https://github.com.mcas.ms/pdavis68/RepoMapper)
Instructions for setting up as an [MCP Server](https://github.com.mcas.ms/pdavis68/RepoMapper#running-as-an-mcp-server)

Add RepoMapper MCP Server

---

README.md

Python Streamable HTTP Server you can run locally to interact with [memvid](https://github.com/Olow304/memvid) storage and semantic search.

added memvid-mcp-server

---

README.md

The `@intlayer/mcp` server offers seamless IDE integration for developers using [Intlayer](https://github.com/aymericzip/intlayer), an internationalization library tailored for modern JavaScript and TypeScript projects using AI.
By connecting your IDE to this MCP server (e.g., in [Cursor](https://www.cursor.so)), you get instant access to:
**CLI integration** – Inline guidance and command completion for Intlayer’s CLI tooling. (list / build / pull / push / fill dictionaries)
***Integrated access to the documentation** – Provide access to the Intlayer doc to the IDE
– To add into your `.cursor/mcp.json`.
Ideal for teams working with multilingual content, component-based architectures, and modern frameworks like Next.js. Perfectly bridges AI and content localization.

Add intlayer into coding agent list

---

README.md

This pull request adds the following entry to the list of MCP servers:
- [sascharo/gxtract](https://github.com/sascharo/gxtract) 🐍 ☁️ 🪟 🐧 🍎  
GXtract is a MCP server designed to integrate with VS Code and other compatible editors ([documentation](https://sascharo.github.io/gxtract)).  
It provides a suite of tools for interacting with the GroundX platform, enabling powerful document understanding capabilities directly within your development environment.
This addition helps users discover and leverage GXtract for enhanced document processing and integration with GroundX.

Add GXtract MCP Server: Integration for GroundX Platform in VS Code

---

README.md

Removing the old gdrive mcp server (not accessible anymore) and updating with one of the best I could find and try.

Update GDrive mcp server on README.md

---

README.md

This PR adds the HumanSignal/label-studio-mcp-server to the Data Science Tools section of the README.md.
- Added entry for HumanSignal/label-studio-mcp-server
- Placed in alphabetical order within the Data Science Tools section
- Includes tags: 🎖️ 🐍 ☁️ 🪟 🐧 🍎 (Official, Python codebase, Cloud Service (local or cloud), Windows, Linux, macOS)
- Added a description highlighting project, task, and prediction management for Label Studio data labeling workflows
- Create, manage, and automate Label Studio projects, tasks, and predictions
- Streamlines data labeling workflows for machine learning and annotation teams
- Supports integration with LLMs and automation tools via MCP
This contribution follows the guidelines outlined in CONTRIBUTING.md.

Added Label Studio MCP to data science tools

---

README.md

Adding [FIXParser](https://fixparser.dev) to the list. FIXParser has a MCP server option during instantiation. AI-agents can receive and react to market data, sending orders, quotes and more.

Add new FIXParser MCP server

---

README.md

Added Trade Agent's MCP server to the **Finance & Fintech** category. Also reordered some which were out of order.

Alphabetize Finance Category and add Trade Agent Server to README.md

---

README.md

The Bluesky integration is not, as currently stated, provided by the modelcontextprotocol project/org. This PR fixes the attribution.

fix Bluesky attribution

---

README.md

We, at [BoldSign](https://boldsign.com/), have implemented a BoldSign MCP server to let users search, request, and manage e-signature contracts. The server contains various tools that interact with the BoldSign API.
Official repository of the MCP server: https://github.com/boldsign/boldsign-mcp
Official NPM package: https://www.npmjs.com/package/@boldsign/mcp

Add BoldSign MCP

---

README.md

👋 
Adding [MCPJungle](https://github.com/duaraghav8/MCPJungle) to the list of Aggregators.
MCPJungle is a self-hosted MCP Registry + Proxy to allow enterprises to manage all their MCP Servers in one place and AI Agents to access all tools from a single MCP server.

Add MCPJungle to aggregators

---

README.md

This pull request adds the `shadcn-ui-mcp-server` to the list of awesome MCP servers.
This server provides AI assistants with seamless access to shadcn/ui v4 components, blocks, demos, and metadata, which is useful for AI-assisted UI development.
The server has been added to the "Developer Tools" section, maintaining the alphabetical order as specified in the contribution guidelines.

Add new shadcn ui mcp server

---

README-ja.md
README.md

This pull request aims to add the [Optuna MCP server](https://github.com/optuna/optuna-mcp) to the list in README.md
- Added a new entry about Optuna to the "Data Science Tools" category of README.md
- In the Japanese README.md, created the "Data Science Tools" category and added the Optuna entry into it.

Add Optuna MCP

---

README.md

A [Model Context Protocol (MCP)](https://modelcontextprotocol.io/) server that integrates with [Pica](https://picaos.com/), enabling seamless interaction with various third-party services through a standardized interface. This server provides direct access to platform integrations, actions, execution capabilities, and robust code generation capabilities.

feat: add official MCP for Pica

---

README.md

This PR adds the kill-process-mcp server (https://github.com/misiektoja/kill-process-mcp).
This server provides a way for any LLM to list and terminate OS processes via natural language queries.

Add kill-process-mcp server

---

README.md

This PR adds two MCP servers under the 🎯 Marketing category:
- [stape-io/stape-mcp-server](https://github.com/stape-io/stape-mcp-server): An MCP server for interacting with the Stape API using AI tools like Claude and IDEs like Cursor.
- [stape-io/google-tag-manager-mcp-server](https://github.com/stape-io/google-tag-manager-mcp-server): A Google OAuth-enabled MCP server exposing the GTM API for remote access to containers, tags, and workspaces.
These additions support server-side tracking, automation, and marketing analytics use cases.

Add Stape and GTM MCP servers under Marketing section

---

README-zh.md
README.md

this mcp server can convert any OpenAPI/Swagger-compliant REST API into Model Context Protocol (MCP) format, enabling AI assistants to understand and call your APIs.

Add new mcp-swagger-server server

---

README.md

- Adds Google Sheets MCP to the Databases section.  
- Your AI Assistant's Gateway to Google Sheets! 25 powerful tools for seamless Google Sheets automation via MCP.
- Repo: https://github.com/henilcalagiya/google-sheets-mcp  
- PyPI: https://pypi.org/project/google-sheets-mcp/
- Language/stack: Python (🐍)  
- Scope: Local (🏠)  
- Status: Published on PyPI; includes config and usage docs.

Add Google Sheets MCP

---

README.md

Add [triplyfy-mcp](https://github.com/helpful-AIs/triplyfy-mcp), an MCP server to plan and manage itineraries in Triplyfy with interactive maps. Users can create/read/update trips, organize places and notes via drag-and-drop, and search/save flights.

Add triplyfy-mcp to servers list

---

README.md

- Adding [OMOP MCP server](https://github.com/OHNLP/omop_mcp) to the Biology, Medicine and Bioinformatics section.
- Map clinical terminology to OMOP concepts for healthcare data standardization and interoperability. This server enables AI agents to work with medical vocabularies (SNOMED, LOINC, RxNorm, etc.) and convert them to standardized OMOP concepts.
- The server underwent evaluation by medical experts with hundreds of medical concepts for usability; a pre-print for this research is currently under review.

Add OMOP MCP server for clinical terminology mapping

---

README.md

Adding deploy-mcp to the Developer Tools section following the contributing guidelines.
deploy-mcp provides universal deployment tracking for AI assistants with live status badges and deployment monitoring for Vercel, Netlify, and Cloudflare Pages.
- **Repository:** https://github.com/alexpota/deploy-mcp
- **Category:** Developer Tools (deployment monitoring enhances development workflow)
- **Alphabetical position:** Correctly placed between delano/postman-mcp-server and docker/hub-mcp
- **Format compliance:** Follows existing format with proper emoji indicators (📇 ☁️ 🏠)
- Live deployment status badges at https://deploy-mcp.io
- Real-time webhook integration for deployment updates
- MCP tools for AI assistants to query deployment status
- Support for Vercel, Netlify, and Cloudflare Pages

Add deploy-mcp to Developer Tools section

---

README.md

This PR adds the mcp-rubber-duck MCP server to the Coding Agents category.
mcp-rubber-duck is an MCP server that bridges to multiple OpenAI-compatible LLMs and serves as your AI rubber duck debugging panel. It allows explaining problems to various AI "ducks" and getting different perspectives.
Features:
- 🦆 Multiple LLM provider support (OpenAI, Gemini, Groq, Ollama, etc.)
- 💬 Conversation management with context
- 🏛️ Duck Council - get responses from all LLMs at once  
- 🔗 MCP Bridge support for extended functionality
- 📦 Available on NPM and Docker
The server is properly categorized under Coding Agents as it's specifically designed for programming assistance and debugging workflows.

Add mcp-rubber-duck to Coding Agents category
