punkpeye/awesome-mcp-servers

- README.md
https://github.com/reeeeemo/ancestry-mcp
> Add reeeeemo/ancestry-mcp

- README.md
https://github.com/fatwang2/search1api-mcp
> add fatwang2/search1api-mcp

- README.md
Add local/cloud labels to API connectors
> Extend Legend With Cloud/Local API connectors

- README.md
Thanks for reaching out about this list, making it and an awesome post you wrote to help me understand how to even build it.
This adds a link to my MCP server for reading your apple notes locally.
> Add new server for reading your Apple Notes 

- README.md
👋 Adding FastMCP to the frameworks section
> Add FastMCP

- README.md
added github star history in readme file
> added github star history in readme file 

- README.md
Perhaps this should go into a separate section for "Videos"?
> Add a video tutorial for a SQLite database

- README.md
This PR adds the mcp-gsuiter server which right now supports various gmail and google calendar functions.
I was not sure about the category but I think communication is correct.
> Added gsuite (gmail + calendar) MCP Server

- README.md
Adding mcp-atlassian - a Python MCP server for Confluence search and content access
> Add mcp-atlassian: Confluence integration server

- README.md
Description now also includes calendar
> updated text for mcp-gsuite

- README.md
MCP server for browser automation using Playwright
> docs: update readme with mcp-server-playwright

- README.md
Add NS Travel Information MCP Server under new Travel & Transportation category
> Add NS Travel Information MCP Server

- README.md
> Add clients

- README.md
> Add Perplexity MCP Server 

- README.md
The MCP Chatbot is a simple yet powerful CLI chatbot that integrates tool servers with any OpenAI-compatible LLM API. 
This example implementation can serve as a foundation for more complicated builds, allowing developers to expand upon its functionality and integrate additional features as needed.
> Add MCP Chatbot to the list of clients

- README.md
Web research MCP server with these capabilities:
* Google search and visit any webpage + extract the content
* Do deep web research with a prebuilt agentic research prompt
* Take webpage screenshots
> Update README.md to add mcp-webresearch server

- README.md
Adding yet another MCP server...
> Adding the simple arXiv MCP

- README.md
This allows super easy connection of any HTTP / REST API to claude.
Example using simple "petstore" API - swap in a different open api json spec and connect to your own server.
> Add openapi-mcp-server

- README.md
Graph-based memory server with dynamic tools and entity types defined by user.
Includes a [separate tool](https://github.com/CheMiguel23/MemoryMesh/discussions/3) to easily add and edit existing schemas which are processed by the server and guide AI to create and memorize content that user wants.
> Add MemoryMesh

- README.md
Looks like this server does not exist.
> Revert "Added terminal mcp server"

- README.md
Adding a separate kubernetes cluster mcp server written in typescript with slightly different goals like helm chart compatibility in the future.
> Adding typescript implementation of kubernetes mcp server

- README.md
Add Finance and Fintech section, along with CoincapMCP
> Add Finance and Fintech section, along with CoincapMCP

- README.md
Hi, just thank you for this awesome.
We have an open source project with 5K star and we have support to run MCP servers as langchain tools as mcp client.
Thanks.
> doc: Added another mcp client

- README.md
Hey,
I've updated the readme in the "Other Tools" section to include the web based UI we built for managing MCP servers for Claude Desktop
> Add MCP Manager Web UI

- README.md
Adding Data Science Tools Section and adding mcp-server-data-exploration tool under this section.
> Update README.md to add Data Science Tools Section

- README-zh.md
- README.md
- synchronous update README-zh
- add OpenDataMCP/OpenDataMCP
- add tinybirdco/mcp-tinybird
- add boilingdata/mcp-server-and-gw
- add lightconetech/mcp-gateway
- add mark3labs/mcphost
> Update README.md And README-zh.md

- README.md
Adding the MCP server for accessing the PubMed database of medical papers.
> Adding mcp-simple-pubmed

- README.md
Running commands and scripts makes it possible to do the work of many other MCP servers, with a single tool call. Definitely deserves its own category
> Split out a new category for running commands.

- README-ja.md
- README-zh.md
- README.md
Thank you for the great list!
I’d like to add Apify's RAG Web Browser to the search section.
I didn’t place it in alphabetical order as per the guidelines because the existing order was already inconsistent.
> Add an MCP server for Apify's RAG Web Browser

- README.md
MCP Server for the Shodan API .
> Add new Shodan MCP server

- README.md
Added my Home Assistant MCP to the list
> Added tevonsb/homeassistant-mcp

- README-ja.md
- README.md
MCP Text Editor Server is designed to facilitate safe and efficient line-based text file operations in a client-server architecture. It implements the Model Context Protocol, ensuring reliable file editing with robust conflict detection and resolution. The line-oriented approach makes it ideal for applications requiring synchronized file access, such as collaborative editing tools, automated text processing systems, or any scenario where multiple processes need to modify text files safely. The partial file access capability is particularly valuable for LLM-based tools, as it helps reduce token consumption by loading only the necessary portions of files.
> add tumf/mcp-text-editor

- README.md
I mistook the product, let me update please 🙏
> fix mcp-shell-server to mcp-text-editor

- README.md
Added an integration with snowflake that has feature parity with the reference PostgreSQL and SQLite servers. It additionally makes write operations opt-in for security purposes.
> Added snowflake integration

- README.md
> Add ZeparHyfar/mcp-datetime

- README.md
As an alternative for the [Python-based MySQL MCP server](https://github.com/designcomputer/mysql_mcp_server)
> Add Node.js-based MCP MySQL server

- README.md
MCP Server for VirusTotal API and Maigret OSINT Tool
> Add VirusTotal and Maigret MCP Servers

- README.md
Added LangChain.js client that provides MCP tools to LangChain and LangGraph agents
> Added LangChain.js client

- README.md
This adds a new Model Context Protocol server for accessing Pinecone - a cloud based vector database.
> Add pinecone based mcp server

- README.md
Read and analyze online GitHub repositories with LLM.
Inspired by gitingest.com
> Add mcp-git-ingest

- README.md
Hi,
I've added [cognee](https://www.cognee.ai/) to the list of the supported memory tools
> Add cognee MCP to memory list

- README.md
Add clojars mcp server which allows look up of latest clojure dependency versions
> Update README.md to add link to a clojars mcp server

- README.md
Adding a Python CLI client that enables MCP for all major providers,
> Add "console-chat-gpt" client

- README.md
I've added 'mcp-aoai-web-browsing' to the list.
> Add "mcp-aoai-web-browsing" server

- README.md
Added a link to Contentful MCP server to the Other-section
> Add Contentful MCP server to "Other"

- README.md
Interact with Twitter search and timeline
> Add mcp-twikit

- README.md
add link to Fireproof MCP database server
> link to Fireproof MCP database server

- README.md
changed the repository category to browser-automation.
> changed the repository category

- README.md
Add mamertofabian/mcp-everything-search to File Systems category. This server provides:
- Fast file search capabilities using Everything SDK
- Windows-specific implementation
- Complements existing filesystem servers with specialized search functionality
> Update README.md - Add Everything Search to File Systems section

- README.md
Adds a new model context protocol to the README for the alpha vantage API.
> Add Alpha Vantage mcp server

- README.md
Description
This pull request introduces mcp-pandoc, a Model Context Protocol (MCP) server for seamless document format conversion. It supports Markdown, HTML, and plain text conversions, with additional formats like PDF, docx, and csv in development.
Motivation and Context
This addition addresses the need for a versatile document format conversion tool when using Claude.
By leveraging Pandoc's robust capabilities, mcp-pandoc provides developers and users with a streamlined solution for transforming content between popular document formats while maintaining formatting and structure.
> feat(mcp-pandoc): A file format conversion mcp server

- README.md
An MCP server for interacting with wolfram alpha API.
> Add SecretiveShell/MCP-wolfram-alpha

- README.md
> Update README.md – Add mcp-zotero

- README.md
Minor readme content change for mcp-pandoc. Recently added support for .pdf and .docx. Updated its description accordingly.
> docs(mcp-pandoc): Updated content to include recently added feature

- README.md
adding mcp-geo geocoding mcp server
> adding mcp geo

- README.md
It's a TS version that can be run either with NPX or in a Docker container.
Tested and verified both options.
> Add SearXNG MCP to the README.md

- README-ja.md
- README-zh.md
- README.md
added entries for piapi.ai mcp server
> Add new server

- README.md
Add https://github.com/sparfenyuk/mcp-proxy to the list of MCP servers
> Add sparfenyuk/mcp-proxy to list of MCP servers

- README.md
Added windows icon for maigret, shodan, and virustotal.
> add dnstwist server and update icons

- README-ja.md
- README-zh.md
- README.md
1. Add Google News MCP Server 
2. Add the content in Chinese README and Japanese README that is not synchronized with the English README
---
Adding a new MCP server that provides Google News search capabilities via SerpAPI integration. This server enables LLMs to search and access news articles with language/region support, topic categorization, and comprehensive story coverage.
- Server: google-news
- Changes to: New server implementation with SerpAPI integration
Currently, there is no dedicated news search capability in the MCP ecosystem. This server fills this gap by providing:
- Structured access to news articles and topics
- Multi-language and region support
- Automatic news categorization
- Full story coverage capabilities
These features enable LLMs to better engage with current …
> Add Google News MCP Server & Add the content in Chinese README and Japanese README that is not synchronized with the English README 

- README.md
> A Model Context Protocol (MCP) server that enables free web searching using Google search results, with no API keys required.
- Search the web using Google search results
- No API keys or authentication required
- Returns structured results with titles, URLs, and descriptions
- Configurable number of results per search
> feat: Added free websearch

- README.md
Repo : https://github.com/mediar-ai/screenpipe
> Added Screenpipe MCP Server

- README-zh.md
- README.md
Compared with other playwrights, two features have been temporarily added:
1. When a click causes a new page to be created, subsequent operations operate from the new page.
2. All text rendered on the web page can be obtained, which is more suitable for llm processing
> add playwright server

- README.md
This adds the [Video Editor MCP Server](https://github.com/burningion/video-editing-mcp?tab=readme-ov-file#video-editor-mcp-server), which allows you to Add, Analyze, Search, and Generate Video edits.
> Add Video Editor MCP

- README-ja.md
- README-zh.md
- README.md
Add https://github.com/marimo-team/codemirror-mcp
> add codemirror-mcp

- README-ja.md
- README-zh.md
- README.md
Hi thank you for all your work on MCP here on github and on the Discord!
Please consider adding this project. The ordering is a bit broken already, so added it at the end in the Databases section :)
> Add mcp-alchemy server

- README.md
See https://github.com/grafana/mcp-grafana, released yesterday.
Thanks for maintaining the list!
> feat(readme): add Grafana MCP server to Monitoring section

- README-ja.md
- README-zh.md
- README.md
An MCP server application that sends various types of messages to the WeCom group robot.
> add mcp-wecombot-server

- README.md
Those 2 MCP servers provide integration capabilities for both Jira and Confluence :
- **Confluence Tools**:
- **Execute CQL Search**: Perform CQL queries to search for Confluence pages.
- **Get Page Content**: Retrieve contents of specific Confluence pages.
- **Installation Instructions**:
- To integrate with Claude Desktop, update the server configuration specific to your operating system. Utilize `~/Library/Application Support/Claude/claude_desktop_config.json` on MacOS or `%APPDATA%/Claude/claude_desktop_config.json` on Windows.
```json
{
"Confluence communication server": {
"command": "node",
"args": [
"/PATH_TO_THE_PROJECT/build/index.js"
],
"env": {
"CONFLUENCE_URL": "https://XXXXXXXX.atlassian.net/wiki",
"CONFLUENCE_API_MAIL": "Your email",
"CONFLUENCE_API_KEY": …
```
> JIRA and CONFLUENCE MCP servers

- README.md
https://docs.spring.io/spring-ai-mcp/reference/overview.html
> Add Java and Spring MCP SDK link

- README-ja.md
- README-zh.md
- README.md
Add GTasks, Fetch, and Markdownify MCP. Used Claude for translations into JP and ZH READMEs.
> feat: add three MCP servers

- README.md
MCP server that is added includes detailed setup instructions and real-world LLM examples on how it can be used. It has 23 tools to it's availability can manage every singe endpoint that is related to Netskope's ZTNA solution. From on-premise publishers, to troubleshooting to the entire policy CRUD framework and everything in between.
> Fixed line identation and added new MCP for Netskope's Zero Trust Network Access framework

- README.md
A Model Context Protocol server for interacting with TastyTrade brokerage accounts. This server enables Large Language Models to monitor portfolios, analyze positions, and execute trades through the TastyTrade platform.
Please note that tasty-agent is currently in early development. The functionality and available tools are subject to change and expansion as development continues.
- Python 3.12 or higher
- [uv](https://docs.astral.sh/uv/) package manager
- A TastyTrade account
Install uv if you haven't already:
```bash
curl -LsSf https://astral.sh/uv/install.sh | sh
```
We will use `uvx` to directly run tasty-agent:
```bash
uvx tasty-agent
```
The server requires TastyTrade credentials. For security, these are set up via command line and stored in your system's keyring (Keychain on macOS, …
> Add server for placing trades with tastytrade API

- README.md
Link to the MCP server for [iaptic](https://www.iaptic.com).
> Add iaptic mcp server

- README-ja.md
- README-zh.md
- README.md
Add Actors MCP server for Apify's Actors (English, Japanese, and Chinese (chatgpt translation only))
Thank you for keeping this list of MCP Servers!
I also like the MCP clients one.
> docs: Add Actors MCP server for Apify's Actors

- README.md
Small PR to add my MCP ORKL server https://orkl.eu/
> Adding the ORKL MCP Server

- README.md
Adds [SQL analyzer server](https://github.com/j4c0bs/mcp-server-sql-analyzer) to developer tools section. 
Thank you for maintaining this awesome list 🤝
> Add new sql analyzer server

- README.md
[Bitcoin MCP Server Repo](https://github.com/AbdelStark/bitcoin-mcp) - [Bitcoin MCP Server Documentation](https://abdelstark.github.io/bitcoin-mcp/)
A Model Context Protocol (MCP) server that enables AI models to interact with Bitcoin, allowing them to generate keys, validate addresses, decode transactions, query the blockchain, and more.
- **Key Generation**: Create new Bitcoin key pairs — including address, public key, and private key (WIF).
- **Address Validation**: Validate the correctness of a Bitcoin address.
- **Transaction Decoding**: Parse a raw Bitcoin transaction and display its details in a human-readable format.
- **Blockchain Queries**:
- **Latest Block**: Retrieve details about the most recent block (hash, height, timestamp, transaction count, etc.).
- **Transaction …
> Add Bitcoin MCP Server.

- README-ja.md
Thank you for the great awesome!
I noticed that we can improve the Japanese translation and send this small pull request.
> Improve "legend" ja translation: 伝説 -> 凡例

- README-ja.md
- README-zh.md
- README.md
Add Security Audit MCP Server to README files
- [Security Audit MCP Server](https://github.com/qianniuspace/mcp-security-audit) 📇🛡️☁️ 一个强大的 MCP (模型上下文协议) 服务器，审计 npm 包依赖项的安全漏洞。内置远程 npm 注册表集成，以进行实时安全检查。
- [Security Audit MCP Server](https://github.com/qianniuspace/mcp-security-audit) 📇🛡️☁️ A powerful MCP (Model Context Protocol) Server that audits npm package dependencies for security vulnerabilities. Built with remote npm registry integration for real-time security checks.
- [Security Audit MCP Server](https://github.com/qianniuspace/mcp-security-audit) 📇🛡️☁️ 強力なモデルコンテキストプロトコル（MCP）サーバーで、npmパッケージ依存関係のセキュリティ脆弱性を監査します。リモートnpmレジストリ統合を備えたリアルタイムセキュリティチェックを使用して構築されています。
> Add Security Audit MCP Server to README files

- README.md
Excel MCP Server:
- Provides Excel file manipulation capabilities without requiring Microsoft Excel installation
- Built with OpenPyXL
- Supports workbook creation, data operations, formatting, charts, and pivot tables
> docs: add excel-mcp-server to developer tools

- README.md
**Enhanced Supabase MCP Server:**
- supports package distribution (uv, pipx, etc)
- enables read-only SQL query execution
- works with local and remote instances (supports direct and transaction pooling connectors)
- provides pre-built tools to explore db schema, tables that greatly improves LLM tool usage accuracy
**Tests**:
- Has basic test coverage
**Deployment options**:
- can be installed from source (git clone)
- can be installed via package manager (pipx install supabase-mcp-server)
- can be deployed via smithery.ai
> docs: add Supabase MCP Server with SQL query execution 

- README.md
Attio is a next-generation, AI-native Customer Relationship Management (CRM) platform designed to adapt seamlessly to the unique needs of modern businesses. It offers extensive customization, allowing companies to tailor their CRM to match specific workflows and processes. 
The Attio MCP Server is a model context protocol server that connects AI Clientes with Attio.
> add Attio CRM

- README.md
Added ChronulusAI/chronulus-mcp entry.
https://github.com/ChronulusAI/chronulus-mcp
> Added new Chronulus AI server for chatting with forecasting and prediction agents

- README.md
Adds [nickclyde/duckduckgo-mcp-server](https://github.com/nickclyde/duckduckgo-mcp-server) to the search section!
> Add duckduckgo-mcp-server

- README.md
Now this repo supports for both Confluence and Jira products, so that I updated the description.
> Update mcp-atlassian description

- README.md
About [mcp-agent](https://github.com/lastmile-ai/mcp-agent):
> Add mcp-agent framework to readme

- README.md
Add Neon Postgres to the list of MCP servers
https://neon.tech/home
https://github.com/neondatabase/mcp-server-neon
> Add Neon Postgres MCP Server

- README.md
The **investor-agent** is a Model Context Protocol (MCP) server that provides comprehensive financial insights and analysis to Large Language Models. It leverages real-time market data, news, and advanced analytics to help users obtain:
- Detailed ticker reports including company overview, news, key metrics, performance, dates, analyst recommendations, and upgrades/downgrades.
- Options data highlighting high open interest.
- Historical price trends for stocks.
- Essential financial statements (income, balance sheet, cash flow) formatted in millions USD.
- Up-to-date institutional ownership and mutual fund holdings.
- Earnings history and insider trading activity.
The server integrates with [yfinance](https://pypi.org/project/yfinance/) for market data retrieval and …
> Add investor-agent to readme and fix link to tastytrade-agent

- README-zh.md
- README.md
add mcp tavily server nodejs api
https://github.com/kshern/mcp-tavily
> feat: add nodejs tavily mcp server

- README-ja.md
- README.md
Added ``NON906/omniparser-autogui-mcp`` entry.
- https://github.com/NON906/omniparser-autogui-mcp
> Add new NON906/omniparser-autogui-mcp server

- README-zh.md
- README.md
Update en/cn README for the new MCP server, able to query Kafka via SQL
> Add Timeplus MCP server

- README.md
Link to the Model Context Protocol server for [DuckDuckGo Search](https://github.com/zhsama/duckduckgo-mpc-server)
This is a TypeScript-based MCP server that provides DuckDuckGo search functionality.
This has been tested with Claude Desktop application.
None
> Add ts-based duckduckgo web search

- README.md
Adds link to the Make MCP server repo from README.
> Update README.md to include official Make MCP Server

- README-ja.md
- README-zh.md
- README.md
Added `kj455/mcp-kibela` entry.
- https://github.com/kj455/mcp-kibela 
[Kibela](https://kibe.la/) is widely used document tool especially in Japan.
> Add `mcp-kibela`

- README.md
> Update README.md to add browser-use

- README.md
Providing latest cryptocurrency news to AI agents.
> Add cryptopanic-mcp-server

- README.md
Hi,
Here's my **full featured** MongoDB MCP server, which I hope you'll consider adding to your listing:
https://github.com/furey/mongodb-lens
It's significantly more feature packed than the other MongoDB MCP servers you have listed.
Cheers!
🤓👍
> Added "MongoDB Lens" to Databases

- README.md
A mcp  server for tracking cryptocurrency whale transactions.
> Add whale-tracker-mcp.

- README.md
MCP server for Nile Postgres Platform - Manage and query databases, tenants, users, auth using LLMs
> Add Nile MCP server

- README.md
[bytebase/dbhub](https://github.com/bytebase/dbhub) 📇 🏠 – Universal database MCP server supporting mainstream databases.
> chore: add dbbub

- README.md
> Add adx-mcp-server

- README.md
An MCP server that securely interfaces with your iMessage database via the Model Context Protocol (MCP), allowing LLMs to query and analyze iMessage conversations. It includes robust phone number validation, attachment processing, contact management, group chat handling, and full support for sending and receiving messages.
> Add mac_messages_mcp

- README.md
The MCP server provides tools to search Airbnb and get listing details.
> Add Airbnb MCP server to README.md

- README.md
Gives your agent direct access to up-to date Fantasy Premier League (FPL) data.
- Server: `fantasy-pl-mcp-server`
- Provides tools to analyze Fantasy PL players and fixtures
- Provides customized advice to FPL managers based on latest API information
I wanted to be able to ask Claude for advice on my Fantasy Premier League team, analyze players, fixtures and get transfer suggestions but it never had the upto date data and specific Fantasy relevant data (like points scored, price, etc) so I created an MCP server to give Claude direct access via the FPL API.
This MCP server lets Claude users:
- Give Claude direct access to live Fantasy Premier League data
- Use Claude as an FPL AI Assistant
- Ask for personalized advice on their FPL teams
- Get recommendations on players
- Get …
> Add Fantasy PL Community MCP Server

- README.md
This one is registered in official list too. https://github.com/modelcontextprotocol/servers/pull/880#event-16793771157
> Add apache airflow MCP server

- README.md
[jvm-mcp-server](https://github.com/xzq-xu/jvm-mcp-server.git)
This is an implementation project of a JVM-based MCP (Model Context Protocol) server. The project aims to provide a standardized MCP server implementation for the JVM platform, enabling AI models to better interact with the Java ecosystem.
> add JVM MCP Servert

- README.md
[QGIS MCP](https://github.com/jjsantos01/qgis_mcp) connects QGIS to Claude AI through the Model Context Protocol (MCP), allowing Claude to directly interact with and control QGIS. This integration enables prompt assisted project creation, layer loading, code execution and more.
> docs: add QGIS MCP server

- README-ja.md
- README-zh.md
- README.md
A Model Context Protocol server implementation for VRChat that enables fetching user information and friend lists through the MCP standard. The server provides VRChat API integration while maintaining MCP compatibility.
> Add VRChat MCP Server

- README.md
A mcp server that provides real-time and historical Crypto Fear & Greed Index data.
> Add crypto-feargeed-mcp

- README.md
Adding 21st.dev Magic MCP server, one of the fastest growing and lovable MCPs, already featured in 
- https://github.com/modelcontextprotocol
- Top 3 extensions at https://smithery.ai/
- Cline marketplace
> Add: Magic-MCP

- README.md
This MCP server lets you connect to Trino clusters and run queries on them.
> Adding trino MCP server

- README-ja.md
- README-zh.md
- README.md
Hey there!
MCP provides the ability to generate images via Replicate's API
Cheers =)
> Add Replicate API MCP server

- README.md
add a natural language supported database accessing via text-to-sql
> ADD Xiyan MCP server

- README-ja.md
- README-zh.md
- README.md
Add TiDB MCP Server to both zh/en/ja docs
> Add TiDB MCP Server

- README.md
Add xcodebuild mcp server tool
> Add xcodebuild mcp server tool

- README.md
Add GraphQL MCP server that allows querying of GraphQL servers.
> feat: add graphql mcp server

- README.md
> Add raindrop.io mcp server

- README.md
> add quarkus server framework and available mcp servers

- README.md
The `bankless/onchain-mcp` server implements a Model Context Protocol (MCP) server for Bankless Onchain. 
This server serves as a middleware between AI models (LLMs) and blockchain data, allowing LLMs to read contract state, fetch events, and access transaction information across multiple blockchain networks.
1. **Read Contract State**
- Allows reading state from any contract on supported blockchain networks
- Supports method calls with typed inputs and outputs
- Schema: `ReadContractSchema`
2. **Get Proxy Implementation**
- Retrieves the implementation address for proxy contracts
- Schema: `GetProxySchema`
3. **Get Contract ABI**
- Fetches the Application Binary Interface (ABI) for a contract
- Schema: `GetAbiSchema`
4. **Get Contract Source**
- Retrieves the source code and compilation …
> Added bankless/onchain-mcp to README.md

- README.md
This PR adds a reference to the EVM MCP Server in the Finance & Fintech section of the README.md.
- Provides comprehensive blockchain services for 30+ EVM-compatible networks
- Supports reading blockchain state (balances, transactions, blocks)
- Enables interaction with smart contracts
- Handles token operations (native, ERC20, ERC721, ERC1155)
- Includes ENS name resolution for human-readable addresses
The server entry has been added in alphabetical order as per the CONTRIBUTING.md guidelines.
> Add EVM MCP Server to Finance & Fintech section

- README-ja.md
- README-zh.md
- README.md
Add GreptimeDB MCP server to database section.
> docs: add greptimedb mcp

- README.md
A personal MCP (Model Context Protocol) server for securely storing and accessing API keys across projects using the macOS Keychain.
> Update README.md with secure API MCP service

- README.md
- whoami-mcp
- whereami-mcp
- whattimeisit-mcp
- nearby-search-mcp
- dune-analytics-mcp
> Add 5 mcp servers.

- README-ja.md
- README-zh.md
- README.md
Add an interactive mindmap MCP server, support ai client artifacts' preview, or save a HTML file to open in a browser.
This pull request includes updates to the `README` files in 3 languages to add a new entry for the `mindmap-mcp-server` project.
> Add a mindmap mcp server 

- README.md
Also adds a Linux emoji because why not; though then I realized for taskwarrior there is no need to specify since it runs on windows, osx, and linux.
> Add taskwarrior server

- README-ja.md
- README-zh.md
- README.md
MCP server that can execute commands such as keyboard input and mouse movement
https://github.com/NakaokaRei/swift-mcp-gui
> add swift-mcp-gui

- README.md
Add Prometheus MCP server
https://github.com/pab1it0/prometheus-mcp-server
> Add Prometheus MCP server

- README-ja.md
- README-zh.md
- README.md
Hey there!
[mcp-k8s-eye](https://github.com/wenhuwang/mcp-k8s-eye)  is a tool that can manage kubernetes cluster and analyze   kubernetes cluster, application health.
> docs: add mcp-k8s-eye

- README-ja.md
- README-zh.md
- README.md
> Add Gaming section for japanese and chinese readme files

- README.md
* DroidMind is an MCP server to manage and control Android devices via MCP
* Lucidity is an MCP that can analyze your current changeset for common issues encountered when using coding assistants
> Add DroidMind and Lucidity MCP servers

- README.md
- Adds MCP server for controlling Spotify playback and playlist management
- Implements 10 Spotify API operations including search, playback control, and playlist management
- Includes OAuth2.0 authentication flow with auto-token refresh
- Compatible with Claude Desktop and Cursor
- Full documentation for setup and integration
> Add Spotify MCP server

- README.md
> Add an influxdb mcp server

- README.md
Added [mcp-server-giphy](https://github.com/magarcia/mcp-server-giphy) to the Other Tools and Integrations section. This MCP server enables AI models to search and retrieve GIFs from Giphy's vast library through the Giphy API.
> Add Giphy MCP server to Other Tools and Integrations

- README-ja.md
- README-zh.md
- README.md
Adds:
- alibabacloud-tablestore-mcp-server
Thanks!
> Add alibabacloud-tablestore-mcp-server 

- README-ja.md
- README-zh.md
- README.md
Add [mcp-google-sheets](https://github.com/xing5/mcp-google-sheets) to enable access and editing Google Sheets.
> Add MCP Server to access and edit Google Sheets

- README-ja.md
- README-zh.md
- README.md
This PR adds mcp-claude-code to the Developer Tools section of the awesome-mcp-servers repository.
mcp-claude-code is an implementation of Claude Code capabilities using the Model Context Protocol (MCP), enabling AI code understanding, modification, and project analysis with comprehensive tool support. It provides MCP server that implements Claude Code-like
> Add SDGLBL/mcp-claude-code to Developer Tools section

- README.md
Add following five MCP servers:
- pancakeswap-poolspy-mcp: Tracks newly created liquidity pools on Pancake Swap.
- uniswap-poolspy-mcp: Tracks newly created liquidity pools on Uniswap.
- uniswap-trader-mcp: An MCP server for AI agents to automate token swaps on Uniswap.
- token-minter-mcp: Providing tools for AI agents to mint ERC-20 tokens across multiple blockchains.
- thegraph-mcp: Powers AI agents with indexed blockchain data from The Graph.
> Add 5 crypto-related MCP servers.

- README.md
This PR adds the Heurist Mesh Agent MCP server to the Finance & Fintech section of the awesome-mcp-servers list.
The Heurist Mesh Agent is a specialized Model Context Protocol server that provides access to web3 AI agents for blockchain analysis, smart contract security auditing, token metrics evaluation, and on-chain interactions. The server is already listed as a community server in the official Model Context Protocol repository at https://github.com/modelcontextprotocol/servers/tree/main.
This addition expands the available finance and blockchain-focused MCP servers in the awesome list, providing users with more specialized tools for:
- Blockchain data analysis and insights
- Smart contract security audits
- Token metrics evaluation
- On-chain transaction monitoring
- DeFi protocol …
> feat:add heurist-mesh-mcp-server

- README.md
[gitee.com](https://gitee.com) is the biggest version control platform in china，mcp-gitee is the official mcp server
> Add Gitee MCP Server to README.md

- README.md
The Firefly MCP (Management Control Protocol) server is a TypeScript-based server that enables seamless integration with the Firefly platform. It allows you to discover, manage, and codify resources across your Cloud and SaaS accounts connected to Firefly.
> Add Firefly MCP to README

- README.md
Added a Qdrant MCP server to the list of databases MCP servers.
> Added Qdrant MCP server

- README-ja.md
- README-zh.md
- README.md
Adding the bilibili-mcp-js MCP server to the Browser Automation list，thanks
> Add bilibili-mcp-js

- README.md
Add https://github.com/chrishayuk/mcp-cli to the list.
Related https://github.com/chrishayuk/mcp-cli/issues/1
> Add chrishayuk's mcp-cli

- README.md
This adds https://github.com/yWorks/mcp-typescribe mcp server
> Add mcp-typescribe server

- README.md
Added the ROADRecon MCP server, built to analyze data collected by ROADRecon (Dev’d by Dirk-jan Mollema)
> Added ROADRecon MCP Server

- README.md
Adding official [AgentQL](https://www.agentql.com/) MCP server for structured data extraction
> Add AgentQL MCP

- README.md
This PR adds three new MCP servers to the collection:
1. Weather MCP Server
- Provides real-time weather data, forecasts, and historical weather information
- Uses OpenWeatherMap API
- Added to Location Services section
2. Crypto Trader MCP Server
- Provides cryptocurrency market data and analysis
- Uses CoinGecko API
- Added to Finance & Fintech section
3. YFinance Trader MCP Server
- Provides stock market data and analysis
- Uses Yahoo Finance API
- Added to Finance & Fintech section
All servers follow the standard MCP protocol and include proper badges (🐍 for Python, ☁️ for Cloud Service).
- Added Weather MCP to Location Services section
- Added Crypto Trader and YFinance Trader MCPs to Finance & Fintech section
- Updated section descriptions to better reflect the added content
> feat: Add Weather, Crypto, and YFinance MCP Servers to Collection

- README-zh.md
- README.md
Here is the document:
https://open.longportapp.com/docs/llm
> Add new LongPort server.

- README-ja.md
- README-ko.md
- README-zh.md
- README.md
1) Tranlsated the entire README.md into Korean(REAME-ko.md) 
2) Modified existing .md to include Korean README.md
> Add: Korean README

- README.md
Added Manim MCP Server to Art & Culture section
> Added Manim MCP Server to Art & Culture section

- README.md
Adding the GitHub link for the bruno MCP
NPM package: https://www.npmjs.com/package/bruno-mcp
> Add `bruno-mcp`

- README.md
> Add new VOYP MCP server

- README-ja.md
- README-zh.md
- README.md
Interact seamlessly with GitLab repositories to manage merge requests and issues. Fetch details, add comments, and streamline your code review process with ease.
> Add gitlab-mr-mcp

- README.md
This pull request includes a small update to the `README.md` file. The change adds a new repository to the list of related tools.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R502): Added `f/MCPTools` repository to the list of MCP-related tools. MCP Tools is a powerful command-line interface for interacting with MCP servers.
> add f/mcptools

- README.md
Added full blown Data Platforms.
> Data Platforms

- README.md
Add example of an MCP server which can interact with Salesforce instance (send emails on user behalf, validate or deploy code)
> Add Salesforce MCP

- README-ja.md
- README-zh.md
- README.md
https://github.com/higress-group/higress-ops-mcp-server
> Add higress-ops-mcp-server

- README.md
Add following MCP servers to the list:
- jupiter-mcp: For executing token swaps on the Solana blockchain using Jupiter's new Ultra API.
- crypto-indicators-mcp: Providing a range of cryptocurrency technical analysis indicators and strategies.
- token-revoke-mcp: Checking and revoking ERC-20 token allowances across multiple blockchains.
- crypto-sentiment-mcp: Delivering cryptocurrency sentiment analysis to AI agents.
- rug-check-mcp: Detecting potential rug pull risks in Solana meme tokens.
- freqtrade-mcp: Integrating with the Freqtrade cryptocurrency trading bot.
> Add 6 crypto-related MCP servers.

- README.md
> Update README.md to include a new Stata MCP server

- README-ja.md
- README-zh.md
- README.md
This pull request includes updates to the `README` files in multiple languages to add a new MCP server ([yuna0x0/hackmd-mcp](https://github.com/yuna0x0/hackmd-mcp)) that allows AI models to interact with [HackMD](https://hackmd.io).
> Add HackMD MCP server

- README.md
added centralmind/gateway - MCP API generator
> Update README.md - added centralmind/gateway - MCP API generator

- README-zh.md
- README.md
A VMware ESXi/vCenter management server based on MCP (Model Control Protocol), providing simple REST API interfaces for virtual machine management.
> A VMware ESXi/vCenter management server based on MCP

- README-ja.md
- README-zh.md
- README.md
This tool is designed to solve the problem of AI - output files being split due to length limits by quickly and securely merging multiple split files into one complete file. It was created to help users obtain complete AI - output content by first splitting and then merging files, ensuring efficiency and security in the process.
这是一个用于解决 AI 输出文件因长度限制而分块问题的工具，能够快速、安全地将多个分块文件合并为一个完整文件。项目初衷是帮助用户在面对 AI 输出内容长度受限时，通过先分块输出再合并的方式，完整获取所需文件，同时确保合并过程的高效与安全。
github: https://github.com/exoticknight/mcp-file-merger
npm: https://www.npmjs.com/package/@exoticknight/mcp-file-merger
> add File Merger MCP Server

- README-zh.md
- README.md
A Model Context Protocol server that provides network asset information based on query conditions. This server allows LLMs to obtain network asset information and supports querying network asset information by zoomeye dork etc.
> Add ZoomEye MCP Server

- README-ja.md
- README-zh.md
- README.md
[`mcp-server-apple-reminders`](https://github.com/FradSer/awesome-mcp-servers) is an MCP server for interacting with Apple Reminders on macOS.
> Add `mcp-server-apple-reminders`

- README.md
Description:
This pull request introduces a Model Context Protocol (MCP) server that integrates with Notion's API to manage personal todo lists efficiently. The server provides functionalities to add, show, and update tasks within a Notion workspace, making it a valuable tool for users who want to automate and streamline their task management process.
Features:
- Add Task: Allows users to add new tasks to their Notion workspace.
- Show Tasks: Retrieves and displays all tasks from the Notion workspace.
- Update Task: Marks tasks as complete in the Notion workspace.
> Title: Add Notion MCP Server for Managing Todo Lists

- README.md
Hello!
I have added a new section to your awesome list! I believe this section can be used by others in the future to add information related to embedded devices. (Additionally, a very interesting topic that could be added to MCP is home automation (IoT).)
I also added a small MCP example that will help people debug their build issues for ESP chips.
> Add MCP Server to fix ESP build issues

- README-ja.md
- README-zh.md
- README.md
Adding new mcp server - [ntfy-mcp](https://github.com/teddyzxcv/ntfy-mcp)
The MCP server that keeps you informed by sending the notification on phone using ntfy 
- Server:  ntfy-mcp
The motivation behind creating the ntfy-mcp from the need to enhance productivity and maintain workflow continuity in software development. Let user temporarily leave the program but not waiting for end of task.
- Tested using ntfy.sh (official server) with cline and Roo Code.
> Add new ntfy mcp server

- README.md
Add the official Semgrep MCP server github.com/semgrep/mcp
> Add Security > Semgrep MCP server

- README.md
Added Vibe Check Server:
Summary:
The definitive Vibe Coder's sanity check MCP server: Prevent cascading errors in AI workflows by implementing strategic pattern interrupts. Uses tool call "Vibe Check" with LearnLM 1.5 Pro (Gemini API), fine-tuned for pedagogy and metacognition to enhance complex workflow strategy, and prevents tunnel vision errors. 
Links:
https://smithery.ai/server/@PV-Bhat/vibe-check-mcp-server
https://glama.ai/mcp/servers/@PV-Bhat/vibe-check-mcp-server
https://github.com/PV-Bhat/vibe-check-mcp-server
https://mcp.so/server/vibe-check/PV-Bhat
Thanks!
> Add Vibe Check server

- README.md
Add Flipt MCP server https://github.com/flipt-io/mcp-server-flipt
> chore: add Flipt MCP server

- README.md
Adding the Weaviate MCP server to the databases list
> Update README.md -Adding the Weaviate MCP server 

- README.md
Let me know if you'd rather this went into the general section?
> add Code Execution section and mcp-run-python

- README-zh.md
This PR updates the Chinese documentation (README-zh.md) to sync with the latest English version.
此 PR 更新了中文文档（README-zh.md）以与最新的英文版本保持同步。
- Synchronized with the latest English version
- Ensure the location of the newly added MCP servers in the Chinese documentation matches that in the English documentation.
- 与最新的英文版本同步
- 确保新添加的MCP服务器在中文文档中的位置与英文文档中的位置一致。
- Adjusted the order of resources in Chinese documentation to match English version
- Adjusted the order of the table of contents and modules in the Chinese documentation to align with the English documentation.
- Ensured consistent listing order across both languages
- 调整了中文文档里资源链接的顺序，与英文文档保持一致
- 调整了中文文档里目录和模块的顺序，与英文文档保持一致
- 确保两种语言版本中的列表顺序一致
- ✅ Synchronized all sections with the English version
与英文版本同步了所有章节
- ✅Preserved all emoji …
> docs:Synchronize Chinese documentation with updates from English.

- README.md
This is a new Kotlin SDK which implements the latest MCP spec. It is highly testable and functional in nature.
> Add http4k MCP SDK

- README.md
[Bitte Protocol](https://bitte.ai) connects several AI Agents to multiple EVM chains and Near Protocol.
> adds Bitte Protocol MCP Server

- README.md
Integrate the MCP for Mifos X an Open Source Core Banking Solution for Financial Institutions
> Integrate the MCP for Mifos X an Open Source Core Banking Solution for Financial Institutions

- README.md
A Model Context Protocol server enabling Claude to have conversations with ChatGPT and use its web search capabilities, featuring persistent conversation state management via OpenAI's Responses API.
> Add billster45/mcp-chatgpt-responses to Other Tools section

- README.md
> Remove duplicate An MCP Server Integration with Apple Shortcuts

- README.md
Unibase membase is the first decentralized memory layer for AI agents. It stores historical information, interaction records, and persistent data of agents, ensuring their continuity and traceability.
The membase mcp server enables seamless integration with the membase protocol for decentralized storage. It provides functionality to upload and download memory to/from the Unibase DA network.
membase usage: 
Beeper provides a set of tools for interacting with the BSC blockchain, including balance check, balance transfers, token transfers, token swaps in Pancakeswap and beeper reward claims.
beeper usage:
> Add Membase and Beeper MCP Server

- README.md
Add mattermost-mcp-host, open-streetmap-mcp and climatiq-mcp-server
> Add mattermost-mcp-host, open-streetmap-mcp and climatiq-mcp-server

- README.md
- run queries
- knowledge graph memory
- manage Neo4j Aura instances
> Update Neo4j MCP capabilities

- README.md
MCP server for Apple's simctl binary.
> Add simctl-mcp

- README.md
Confluent integration for querying Confluent Kafka and Confluent Cloud via REST APIs.
> Added Confluent MCP server project

- README-ja.md
- README-ko.md
- README-zh.md
- README-zh_TW.md
- README.md
The Lara Translate MCP Server is the official implementation 🎖️ its written in typescript 📇 and it calls Lara APIs ☁️
Updated the icons to better reflect this.
> Updated Lara Translate icons to be more accurate.

- README.md
The Quran MCP Server calls Quran.com APIs ☁️
Updated the icons to better reflect this.
> Updated Quran MCP icon

- README.md
MCP Auto Register
Package to automate the registration of functions and classes from a python package into a FastMCP instance.
Source: https://github.com/JoshuaSiraj/mcp_auto_register
> Add MCP Auto Register

- README.md
Added an entry for Bugsnag MCP. 
* Organization & Project Navigation: Easily browse your Bugsnag hierarchy
* Error & Event Filtering: Find specific issues with powerful filtering options
* Detailed Stacktrace Viewing: See formatted stacktraces with source code context and highlighted error lines
* Exception Chain Visualization: Understand the root cause by viewing the full exception chain
* Project vs. Library Code Distinction: Clearly identify your code vs third-party libraries
* Source Code Context: View relevant code snippets around error locations
* Error Patterns: Identify recurring patterns across multiple errors
* Search Capabilities: Find issues by error class, message, or app version
* Error Details: Get comprehensive information about each error
* Event History: View all …
> Add Bugsnag MCP

- README.md
Add MCP-NixOS server to the community servers section in alphabetical order. This server provides AI assistants with accurate information about NixOS packages, system options, Home Manager settings, and nix-darwin configurations.
MCP-NixOS is a Model Context Protocol server that provides AI assistants with accurate, real-time information about NixOS packages, system options, Home Manager configuration settings, and nix-darwin macOS configurations. It helps prevent AI hallucinations by giving assistants access to verified package information, configuration options, and documentation.
- Server: mcp-nixos
- Changes to: Added new community server with tools for NixOS, Home Manager, and nix-darwin
NixOS and its ecosystem (Home Manager, nix-darwin) have complex configuration options that AI …
> Add MCP-NixOS server to Developer Tools section

- README.md
This pull request includes updates to the `README.md` file, specifically adding new tools and integrations that enhance the development workflow and environment.
New tools and integrations added:
* [`qainsights/jmeter-mcp-server`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R300-R307): JMeter MCP Server for performance testing
* [`qainsights/k6-mcp-server`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R300-R307): Grafana k6 MCP Server for performance testing
* [`qainsights/locust-mcp-server`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R300-R307): Locust MCP Server for performance testing
1. https://github.com/QAInsights/locust-mcp-server
2. …
> Add: JMeter, Locust, and k6 MCP servers for performance testing

- README.md
A powerful and efficient Blockchain address risk scoring API MCP Server, leveraging the BICScan API to provide comprehensive risk assessments and asset information for blockchain addresses, domains, and decentralized applications (dApps).
BICScan is also listed on https://github.com/modelcontextprotocol/servers for official integration.
> Add new BICScan server

- README.md
This PR adds the Chroma MCP server to the README.md under the database category
> Add Chroma MCP server

- README-ja.md
- README-ko.md
- README-zh.md
- README-zh_TW.md
- README.md
- https://github.com/alexbakers/mcp-ipfs
- https://www.npmjs.com/package/mcp-ipfs
- https://hub.docker.com/r/alexbakers/mcp-ipfs
This assumes npm and the prerequisites are met.
```json
{
"ipfs": {
"command": "npx",
"args": ["-y", "mcp-ipfs"],
"env": {
"W3_LOGIN_EMAIL": "your-email@example.com"
}
}
}
}
```
Build the image first (see Build section) or use the pre-built image alexbakers/mcp-ipfs.
```json
{
"mcp-ipfs": {
"command": "docker",
"args": [
"run",
"-i",
"--rm",
"-v",
"/path/to/your/project:/path/to/your/project",
"-e",
"W3_LOGIN_EMAIL",
"alexbakers/mcp-ipfs"
],
"env": {
"W3_LOGIN_EMAIL": "your-email@example.com"
}
}
}
}
```
> Add new mcp-ipfs server

- README.md
https://github.com/ckreiling/mcp-server-docker 
This is a MCP server I created and am actively maintaining - it's featured as a community server on the official server list! https://github.com/modelcontextprotocol/servers?tab=readme-ov-file#-community-servers
> Add ckreiling/mcp-server-docker

- README.md
MCP Server for Bing Search API
> Add bing-search-mcp

- README.md
Updates Strava MCP implementation to remote first, supporting oauth with refresh tokens.
- Full Strava API coverage (activities, clubs, routes, segments, uploads)
- Type-safe with Zod validation & TypeScript
- Modern architecture using @modelcontextprotocol/sdk
- Enhanced features like pagination and streaming exports
- Better error handling and parameter validation
> Update Strava MCP server link in README.md

- README.md
📇 ☁️ - Nocodb database integration, read and write capabilities
Community version of https://nocodb.com/
> add nocodb server

- README.md
I'd like to add Volatility MCP to the list of awesomeness :)
MCP server for Volatility 3.x, allowing you to perform memory forensics analysis with AI assistant. Experience memory forensics without barriers as plugins like pslist and netscan become accessible through clean REST APIs and LLMs. Below are some of the project snippets
> Volatility MCP under Security section. perform memory forensics analysis with AI assistant via neat FASTAPIs

- README.md
Add MCP server for [Dexscreener](https://docs.dexscreener.com/api/reference) open and free API
> add: Dexscreener MCP

- README.md
Adding the job-searchoor MCP server to the list of available MCP servers in the README.md.
- Server: job-searchoor
- Changes to: Added new server to the README.md list
The job-searchoor MCP server provides a useful tool for retrieving and filtering job listings based on time period, keywords, and remote work preferences. Adding it to the list of available MCP servers will increase visibility and adoption.
The server has been tested with Claude AI and the debugger tool from mcp, retrieving job listings with various filtering options such as time periods (e.g., '1d', '1w'), keyword filters, and remote work preferences. All functionality works as expected.
The job-searchoor server is implemented in TypeScript and works with standard MCP clients like Claude. It provides a straightforward API …
> feat: add Job Searcher MCP server to README

- README-ja.md
- README-ko.md
- README-zh.md
- README-zh_TW.md
- README.md
> Add MetaMCP to multiple README files

- README.md
mcp-recon (formerly tellix) is a conversational reconnaissance interface and MCP server built on ProjectDiscovery's httpx and asnmap libraries. It enables AI assistants like Claude to perform HTTP infrastructure analysis through natural language interaction.
- Multiple reconnaissance levels: quick, complete, and full
- Domain analysis and security header inspection
- TLS certificate analysis
- Standalone ASN lookup for IPs, ASNs, and organizations
- Docker-ready with built-in workarounds for httpx limitations
This MCP server bridges the gap between natural language and HTTP infrastructure analysis, making security reconnaissance more accessible through conversational interfaces.
> Add mcp-recon to awesome-mcp-servers list

- README.md
This pull request adds [Anyquery](https://github.com/julien040/anyquery) to the aggregator category. It is an MCP server for more than 40 apps.
> Add Anyquery

- README-ko.md
> Add naver-search-mcp

- README.md
Description
Added Octagon MCP server implementation in README.md. The repository uses official Octagon API.
Server Details
Server:
Changes to:
Motivation and Context
To provide MCP Server connecting to Octagon Agents. This is used by investors and analysts
How Has This Been Tested?
Tested using Claude and Cursor IDE
Breaking Changes
Types of changes
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to change)
Documentation update
Checklist
I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io/)
My changes follows MCP security best practices
I have updated the server's README accordingly
I have tested this with an LLM client
My code …
> Added official Octagon MCP Server

- README.md
Introduced a lightweight MCP server implementation for Wrike, supporting task retrieval, creation, and commenting.
> Add new Wrike MCP server implementation

- README.md
> Add @dealx/mcp-server

- README.md
Added the Official OP.GG Esports MCP server.
> Add OP.GG Esports

- README.md
🐇 Model Context Protocol (MCP) server that provides comprehensive SQLite database interaction capabilities 
https://github.com/jparkerweb/mcp-sqlite
> add mcp-sqlite

- README.md
Add MCP server for CircleCI
https://github.com/CircleCI-Public/mcp-server-circleci
> add: CircleCI MCP Server

- README.md
Adds MCP Server for IP Find location API
> Add MCP Server to interact with IP Find location API

- README-ja.md
- README-ko.md
- README-th.md
- README-zh.md
- README-zh_TW.md
- README.md
add: [yamanoku/baseline-mcp-server](https://github.com/yamanoku/baseline-mcp-server)
> add: Baseline MCP Server

- README.md
Hello, 
Thanks more making this project! I have created a kaggle mcp server that allows you to search and download datasets. Additionally, I added a prompt to create an EDA (Exploration Data Analysis Notebook) in python.
> add kaggle-mcp

- README.md
This PR adds nictuku/meta-ads-mcp to the Marketing section of the awesome-mcp-servers README.
The Meta Ads MCP server enables AI agents to:
- Monitor and optimize Meta advertising performance
- Analyze campaign metrics and ROI
- Adjust audience targeting parameters
- Manage creative assets and content
- Make data-driven recommendations for ad spend and campaign settings
This tool provides seamless integration with Meta's Graph API, with features like automatic token caching, cross-platform support, and image download capabilities for ad creative analysis.
> Add Meta Ads MCP to Marketing section

- README.md
Add `cswkim/discogs-mcp-server` to the Arts & Culture section.
> docs: add discogs mcp server

- README.md
Hey there,
Added following MCP server -> https://github.com/zinja-coder/jadx-ai-mcp
> Add new JADX-AI-MCP server

- README.md
Added an entry for the XRPL MCP server that provides integration with the XRP Ledger. The server allows AI assistants to access account information, transaction history, and network data on the XRP Ledger, with capabilities for querying ledger objects, submitting transactions, and monitoring the network.
> Add new XRPL server

- README.md
Adding https://github.com/dkvdm/onepassword-mcp-server
> Add new 1Password MCP Server to allow secure credential retrieval

- README.md
This PR adds [`doggybee/mcp-server-leetcode`](https://github.com/doggybee/mcp-server-leetcode) to the `🤖 Coding Agents` section.
**mcp-server-leetcode** 📇☁️ 🍎🪟🐧
An MCP server that enables AI models to interact with [LeetCode](https://leetcode.com), supporting:
- 🔍 Problem search by keyword, tag, and difficulty
- 📅 Daily challenge retrieval
- 👤 User profile and submission history
- 🏆 Contest ranking and metadata
- 🧩 Resource-style endpoints (e.g. `leetcode://problem/{slug}`)
Published on npm: [`@mcpfun/mcp-server-leetcode`](https://www.npmjs.com/package/@mcpfun/mcp-server-leetcode)  
Compatible with Claude for Desktop, Smithery, and other MCP-aware LLM clients.
- Language: TypeScript 📇
- Scope: Cloud service ☁️
- Platforms: macOS 🍎, Windows 🪟, Linux 🐧
- License: MIT
- Categorized under `🤖 …
> Add doggybee/mcp-server-leetcode to Coding Agents

- README.md
Hi, I've been working on a way to access remote storage via MCP:
It works on pretty much every storage protocol as a plugin for [Filestash](https://github.com/mickael-kerjean/filestash)
> add Filestash MCP Server

- README.md
nhances any agent's reasoning capabilities by integrating the think-tools, as described in Anthropic's article(https://www.anthropic.com/engineering/claude-think-tool)
> Adds MCP think tools (by anthropic article)

- README.md
🐍 🏠 Model Context Protocol (MCP) Server for Jupyter.
> add: jupyter-mcp-server

- README.md
this is an official mcp server for enabling use of CodeLogic dependency graph analysis in your client
> Add new codelogic-mcp-server

- README-zh.md
**MCP-Jina-AI is a powerful MCP (Model Control Protocol) tool that integrates Jina.ai's reader service to transform web content into large language model (LLM) friendly formats. It provides a simple and efficient way to convert web pages into structured text, making it easier for AI models to process.**
- Easy URL content extraction
- Automatic conversion to LLM-friendly format
- Clean and structured output
- Fast and reliable processing
- Built with Go for high performance
The server is implemented in Go(🏎️) and is self-hostable (🏠). Repository link: https://github.com/kealuya/mcp-jina-ai
Thank you
> Add MCP-Jina-AI MCP Server

- README.md
Databricks Genie MCP Server
A Model Context Protocol (MCP) server that connects to the Databricks Genie API, allowing LLMs to ask natural language questions, run SQL queries, and interact with Databricks conversational agents.
> Added MCP for Databricks Genie

- README.md
Add Model Context Protocol (MCP) server that interacts with Shopify Dev.
https://shopify.dev/changelog/mcp-server-for-the-shopify-dev-assistant
> Add Shopify MCP server

- README.md
This PR adds [metmuseum-mcp](https://github.com/mikechao/metmuseum-mcp) to the Art & Culture catagory.
This Server leverages the [The Metropolitan Museum of Art Collection API](https://metmuseum.github.io/) to allow users to discover works of art from The Met's collection. If they have images available it will be displayed and added as a Resource to the server.
> Added metmuseum-mcp to Art & Culture section

- README.md
An MCP server that provides real-time funding rate data across major crypto exchanges.
> Add funding-rates-mcp

- README.md
Requesting addition of the [Zaturn MCP server](https://github.com/kdqed/zaturn) under Data Platforms, with my edit
> Add new Zaturn MCP Server

- README.md
- bridge-rates-mcp: Delivering real-time cross-chain bridge rates and optimal transfer routes to  onchain AI agents.
- etf-flow-mcp: Delivering crypto ETF flow data to power AI agents' decision-making.
> Add 2 crypto-related MCP servers

- README.md
Add support for Polygon.io's MCP Server. Example prompt:
> What was the closing price yesterday for AAPL?
> Add Polygon.io MCP Server

- README.md
Armor Model Context Protocol (MCP) gives developers full access to the blockchain functionality of Armor Wallet. This includes cross-chain swaps, token data, bridging, wallet management, limit orders, staking, and many other features. With the Armor MCP, developers can integrate a complete suite of crypto tools available to their AI Agents quickly and easily for fast, reliable AI Agent development.
> Add new armor-crypto-mcp server

- README.md
Add Currents to the Dev Tools category
> Add Currents

- README.md
Adding a new bilibili-mcp server with a function get_popular(top_k: int = 3), which fetches the top k trending videos of the day.
> Add new bilibili-mcp server (trending videos)

- README.md
this PR adds an entry for the Melrōse MCP server which allows you to play musical expression (melrōse language) using a MIDI connected device.
Example prompt:  "play the notes of Für Elise"
> add melrose-mcp server

- README.md
This PR introduces a new MCP server implementation, Node.js Sandbox MCP Server, which provides on-the-fly JavaScript execution in isolated Docker containers.
> Add new Node.js MCP server

- README-ja.md
- README-ko.md
- README-pt_BR.md
- README-zh.md
- README-zh_TW.md
- README.md
An image generation tool based on Google's Imagen 3.0, providing services through MCP (Model Control Protocol).
> Add imagen3-mcp

- README.md
> added GhidraMCP

- README.md
These is a advanced version of twitter MCP where you can also manage the replies of the tweets and get sentimenal anaylsis.
> Add new Twitter MCP 

- README.md
Adds [openai-gpt-image-mcp](https://github.com/SureScaleAI/openai-gpt-image-mcp) to the list. This server provides OpenAI GPT image generation and editing via MCP.
> Add openai-gpt-image-mcp to awesome-mcp-servers

- README-ja.md
- README-ko.md
- README-pt_BR.md
- README-th.md
- README-zh.md
- README-zh_TW.md
- README.md
[chart](https://github.com/antvis/mcp-server-chart): A Model Context Protocol server for generating charts using [AntV](https://github.com/antvis/).
This is a TypeScript-based MCP server that provides chart generation capabilities. It allows you to create 15+ types of charts through MCP tools.
```json
{
"mcp-server-chart": {
"command": "npx",
"args": [
"-y",
"@antv/mcp-server-chart"
]
}
}
}
```
> docs: add mcp-server-chart of AntV

- README-zh.md
- README.md
An MCP server for accessing professional financial data, supporting multiple data providers such as Tushare.
> Add finData mcp server

- README.md
DICOM-MCP is a server for interacting with DICOM systems, which are used to store medical imaging data and reports. 
An example interaction:
```
---------------------------------------------------------------------
🧑‍⚕️ User: "Any significant findings in John Doe's previous CT report?"
🧠 LLM → ⚙️ Tools:
query_patients → query_studies → query_series → extract_pdf_text_from_dicom
💬 LLM Response: "The report from 2025-03-26 mentions a history of splenomegaly (enlarged spleen)"
🧑‍⚕️ User: "What's the volume of his spleen at the last scan and the scan today?"
🧠 LLM → ⚙️ Tools:
(query_studies → query_series → move_series → query_series → extract_pdf_text_from_dicom) x2
(The move_series tool sends the latest CT to a DICOM segmentation node, which returns volume PDF report)
💬 LLM Response: "last …
```
> Update README.md DICOM-MCP

- README.md
This MCP let's you play chess against the LLM.
> Add mcp-chess

- README.md
it now lives in its own git repository
> update github repository for melrose-mcp

- README.md
MacOS Resource Monitor is a lightweight MCP server that exposes a REST API endpoint for monitoring system resources. It analyzes CPU and memory usage, identifies the most resource-intensive processes, and provides actionable suggestions to improve your Mac's performance.
> A Model Context Protocol (MCP) server that identifies resource-intensive processes on macOS and provides performance improvement suggestions.

- README.md
> Add Salesforce MCP server

- README.md
This PR integrates the new TimLukaHorstmann/mcp-weather module under the Location Services section. It provides weather data support via a custom API, enabling localized weather retrieval for downstream components in the MCP ecosystem.
> Add new TimLukaHorstmann/mcp-weather under Location Services

- README.md
Add stass/exif-mcp, MCP server that allows one to examine image metadata like EXIF.
> Update README.md: add exif-mcp

- README.md
Also directly available on NPM:
https://www.npmjs.com/package/fastly-mcp-server
> Add the MCP server for Fastly

- README.md
https://github.com/olalonde/mcp-human
> Add mcp-human

- README.md
MCP Server for the Aiwen IP Location
> add aiwen ip geolocation

- README.md
Adds GrowthBook's official MCP Server
- https://glama.ai/mcp/servers/@growthbook/growthbook-mcp
> Add GrowthBook server

- README.md
Adds the PostHog MCP server to the dev tools section
> Add PostHog to dev tools

- README.md
https://github.com/MarketplaceAdPros/amazon-ads-mcp-server for integrating with Amazon Advertising
> added amazon-ads-mcp-server

- README.md
I'm also on the Discord server !
> Adding homebrew-mcp

- README.md
Access real-time X/Reddit/YouTube data directly in your LLM applications with search phrases, users, and date filtering.
Powered by SN13 of Bittensor: https://www.tao.app/subnet/13
Github repo of SN13: https://github.com/macrocosm-os/data-universe
Regards,
Volodymyr
> MacroCosmos Social Media MCP

- README.md
Add **Odoo MCP Server** to the awesome MCP servers list.
This server bridges AI assistants with **Odoo ERP** systems, enabling natural language interaction with business databases including customer records, product catalogs, sales orders, and invoices.
**The server provides**:
- Full CRUD operations on Odoo models
- Secure authentication (API key/username+password)
- Smart field selection and data formatting
- Comprehensive access control
- Support for all major MCP clients
Perfect for businesses using Odoo who want to leverage AI for data analysis, reporting, and business process automation.
> Add Odoo MCP Server for Odoo ERP database integration

- README.md
A server using C SDK mentioned in https://github.com/punkpeye/awesome-mcp-devtools?tab=readme-ov-file#cc, it is used to help LLM convert code snippets into corresponding ASTs.
> Add new code-to-tree server

- README.md
This PR adds the `sunriseapps/imagesorcery-mcp` server to the 'Multimedia Process' category in the `README.md` files.
**Server Details:**
- **Name:** [sunriseapps/imagesorcery-mcp](https://github.com/sunriseapps/imagesorcery-mcp)
- **Description:** ComputerVision-based 🪄 sorcery of image recognition and editing tools for AI assistants.
- **Language:** 🐍 Python codebase
- **Scope:** 🏠 Local Service
- **Compatible OS:** 🐧 🍎 🪟 all of them
The server has been added in alphabetical order within the 'Multimedia Process' section, following the guidelines in `CONTRIBUTING.md`.
> Add new ImageSorcery server

- README.md
Add joelio/stocky to the Search & Data Extraction section
- MCP server for searching royalty-free stock photography
- Supports Pexels and Unsplash APIs with multi-provider search
- Features rich metadata, pagination, and async performance
- Enables AI assistants to find and access high-quality images
- Python implementation with cloud and local deployment support
> feat: add stocky MCP server for stock photography search

- README.md
This PR adds a comprehensive NCBI/PubMed literature search server to the Search & Data Extraction category.
- **Comprehensive Search**: Full PubMed access with 35+ million articles
- **Advanced Analytics**: Usage tracking and performance monitoring  
- **MeSH Integration**: Medical Subject Headings for precise searches
- **Related Articles**: Discovery through NCBI's algorithms
- **Smart Caching**: Redis + file fallback for performance
- **Batch Processing**: Efficient bulk operations
- **Production Ready**: Extensive documentation and deployment options
This server significantly extends beyond the existing `mcp-simple-pubmed` by adding:
- Analytics and monitoring capabilities
- Advanced caching infrastructure  
- MeSH term integration
- Related articles discovery
- Batch processing for …
> Add NCBI Literature Search MCP Server

- README-ko.md
- README-pt_BR.md
- README-zh.md
- README.md
The project is written in typescript. Change the python emojis to typescript emojis.
> fix typo on ashra-mcp

- README.md
> Add new IP2Location.io server

- README.md
AI‑powered YouTube uploader—no CLI, no YouTube Studio, and no secrets ever shared with LLMs or third‑party apps and all free of cost! It includes OAuth2 authentication, token management, and video upload functionality.
Tested on VS Code and Claude Desktop
Demo: https://www.linkedin.com/posts/anwerj_introducing-youtubeuploadermcp-your-activity-7341431460081385472-u1QX?utm_source=share&utm_medium=member_desktop&rcm=ACoAAATcikoBr1UBYsIDEhkbLNZnaY51zkScG1c
> Adding Youtube Uploader MCP server

- README.md
https://github.com/carsol/monarch-mcp-server 🐍 ☁️ - MCP server providing read-only access to Monarch Money financial data, enabling AI assistants to analyze   transactions, budgets, accounts, and cashflow data with MFA support.
> Add monarch-mcp-server

- README.md
Hey\! I'd love to add Agent MCP to the list. It's a really useful framework for creating multi-agent systems that work together through MCP.
Agent MCP is a framework that enables multiple AI agents to collaborate efficiently using the Model Context Protocol. It's designed for building complex applications where different specialized agents can work on tasks in parallel while sharing context and knowledge.
- Multi-agent task coordination and management
- Shared knowledge base with RAG capabilities
- Real-time visualization dashboard
- Token-based authentication for secure agent communication
- Support for parallel development workflows
I've added it under the **Coding Agents** category since it enables full coding agents that can work autonomously on complex programming tasks:
```markdown …
```
> Add Agent MCP - Multi-agent collaboration framework

- README.md
**Summary**
* Add the Himalayas MCP server to the docs
> Add new Himalayas server

- README.md
> Adding Blender MCP

- README.md
Add the Spacebridge-MCP server, part of [spacebridge.io](https://spacebridge.io)
> add spacebridge-mcp

- README.md
Added a category for RAG (Retrieval augmented generation) - representing systems that provide the full query functionality over an end-to-end RAG system. Added Vectara as the first entry there.
> added vectara and RAG category

- README.md
Add adawalli/nexus - AI-powered web search server using Perplexity Sonar models with source citations and zero-install NPX setup
> docs: add Nexus MCP server to search section

- README.md
Adding Content Core MCP server to the Search & Data Extraction category.
Content Core is a versatile Python MCP server that provides intelligent content extraction from multiple sources:
- **Multi-source extraction**: URLs, documents, videos, and audio files
- **Auto-engine selection**: Intelligent fallback system (Firecrawl → Jina → BeautifulSoup for URLs)
- **Wide format support**: Web pages, PDFs, Word docs, PowerPoints, YouTube transcripts, images with OCR
- **Structured responses**: Consistent JSON format with rich metadata
- **Zero-install option**: Works with `uvx` without local installation
```bash
pip install content-core[mcp]
uvx --from "content-core[mcp]" content-core-mcp
```
```json
{
"content-core": {
"command": "uvx",
"args": ["--from", "content-core[mcp]", …
```
> Add Content Core MCP server for content extraction

- README-zh.md
- README.md
- Add Upstash context7 MCP server to README files
> Add Upstash context7 MCP server to README files

- README.md
- Added ankitmalik84/notion-mcp-server with enhanced functionality
- Features robust error handling and production-ready capabilities
> Add notion-mcp-server - comprehensive Notion MCP integration

- README.md
This PR adds six new MCP server integrations from `@imprvhub` to the awesome-mcp-servers collection, expanding the available tools for automation, monitoring, and data extraction. These additions enhance the repository's catalog with practical servers for browser automation, service monitoring, domain management, and popular platform integrations.
- [imprvhub/mcp-browser-agent](https://github.com/imprvhub/mcp-browser-agent): Browser automation for web workflows, testing, and scraping tasks.
- [imprvhub/mcp-status-observer](https://github.com/imprvhub/mcp-status-observer): Monitor operational status of digital platforms and services.
- [imprvhub/mcp-domain-availability](https://github.com/imprvhub/mcp-domain-availability) Check domain availability across multiple TLDs for registration and …
> Add multiple MCP integrations

- README.md
AutoMobile is a set of tools for mobile automation. You can use it for UI testing or as a development workflow assistant.
The first platform supported is Android with plans to extend to iOS.
> Add AutoMobile to the list

- README.md
This PR adds a comprehensive Jupiter Ultra MCP server that provides complete functionality for Solana DEX operations through Jupiter's Ultra API.
Existing  servers are missing critical functionality and have reliability issues. This new implementation (`araa47/jupiter-ultra-mcp`) provides a complete, production-ready solution with enhanced safety features for LLM interactions.
| Tool | Description | Parameters | Cost |
|------|-------------|------------|------|
| `get_swap_quote` | Get a swap quote and unsigned transaction | `input_mint`, `output_mint`, `amount` | **FREE** |
| `execute_swap_transaction` | Execute a signed swap transaction | `transaction`, `request_id` | **PAID** |
| `get_balances` | Get token balances for a wallet | `wallet_address?` | **FREE** |
| `get_shield` | Get …
> Add new jupiter ultra mcp server on solana

- README.md
Add ZapCap MCP server for video processing
- MCP server for ZapCap API: https://zapcap.ai/
- Video caption and B-roll generation via natural language interface  
- Available on PyPI as zapcap-mcp-server
- 20+ customization options for fonts, colors, animations
installation:
Add to your MCP client `mcp.json` configuration (e.g., Claude Desktop, Cursor and etc.):
```json
{
"zapcap": {
"command": "uvx",
"args": ["zapcap-mcp-server"],
"env": {
"ZAPCAP_API_KEY": "your_api_key_here"
}
}
}
}
```
> Add zapcap-mcp-server for video processing

- README.md
Makes a fix to existing repo link and description (renamed an MCP after adding features)
> Edit repo link + add new feature to description for jupiter-mcp 

- README.md
Adding the new official Docker Hub MCP server
> Add DockerHub Official MCP

- README.md
Hey can you add my project ? also if you have time try and share me your ideas and feedbacks!
> feat: Add ScreenMonitorMCP to community MCP servers

- README-zh.md
- README-zh_TW.md
- README.md
Add yutu: a fully functional MCP server and CLI for YouTube to automate YouTube operation
> docs(readme): add new youtube mcp server - yutu

- README.md
:wave: bringing back https://github.com/punkpeye/awesome-mcp-servers/pull/1021
[dagger/container-use](https://github.com/dagger/container-use?rgh-link-date=2025-06-17T06%3A53%3A58Z) lets each of your coding agents have their own containerized environment. Works with any stack. Powered by open source dagger and git.
> add container-use to code execution

- README.md
This pull request adds the **Kanboard MCP Server** to the list of available Model Context Protocol servers.
The Kanboard MCP Server is a powerful Go-based server that enables seamless integration between AI assistants (like Claude Desktop, Cursor) and the Kanboard project management system. It allows users to manage Kanboard projects, tasks, users, and workflows directly through natural language commands.
**Key Features:**
*   **Seamless Kanboard Integration**: Direct API communication with Kanboard.
*   **Natural Language Processing**: Manage projects using plain English commands.
*   **Complete Project Management**: Handle projects, tasks, users, columns, and more.
*   **Secure Authentication**: Supports both API key and username/password authentication.
*   **High Performance**: Built …
> Add kanboard-mcp server

- README.md
A MCP server for summarizing a user's reddit frontpage or any subreddit by posts and comments.
https://github.com/sinanefeozler/reddit-summarizer-mcp
> Add new reddit-summarizer-mcp server

- README.md
Added [MWGMorningwood/Central-Memory-MCP](https://github.com/MWGMorningwood/Central-Memory-MCP) to the Knowledge & Memory section of the English readme list.
> Update README.md with MWGMorningwood/Central-Memory-MCP

- README.md
This PR adds the NetworkX MCP Server to the awesome list. Key highlights:
🚀 **First-to-market**: The only NetworkX integration in the MCP ecosystem
📊 **13 Operations**: Core graph operations, centrality algorithms, community detection, PageRank, and visualization
🎨 **Visualization**: PNG output with multiple layout options (spring, circular, kamada_kawai)
📦 **Live on PyPI**: `pip install networkx-mcp-server`
✅ **Production Ready**: v1.0.0 with comprehensive tests and documentation
**Repository**: https://github.com/Bright-L01/networkx-mcp-server
**PyPI Package**: https://pypi.org/project/networkx-mcp-server/
**Category**: Data Science Tools
The server enables natural language graph analysis workflows, making NetworkX's powerful graph algorithms accessible through AI conversations.
> Add NetworkX MCP Server - First-to-market graph analysis integration

- README.md
Druid MCP Server - STDIO/SEE MCP Server for Apache Druid by iunera that provides extensive tools, resources, and prompts for managing and analyzing Druid clusters.
https://github.com/iunera/druid-mcp-server 
https://www.youtube.com/watch?v=BqCEWRZbRjU&themeRefresh=1
> Add link to iunera/druid-mcp-server in README.md

- README.md
An MCP server that aggregates live governance proposals from major DAOs.
> Add dao-proposals-mcp

- README.md
Existing JSON MCP tooling are great for performing complex JSON file processing. However, they are not optimised to help LLMs gain understanding of the JSON data efficiently especially when the data your LLM needs is deeply nested / mixed together with irrelevant data.
JSON MCP filter solves this problem in 2 ways
1. Provides LLMs a high level understanding of the JSON file and information structure by reverse engineering the JSON schema into Typescript Types/Interfaces using https://github.com/glideapps/quicktype
2. Allows the LLM to filter out noisy data from the original JSON file by providing its desired schema as an JSON object.
- The JSON MCP Filter server operates entirely on local file systems without requiring external API credentials or network connectivity. 
- The server …
> Add new Large/Complex JSON file filter MCP server

- README.md
Available both as Local (DXT, Node) installation and as Remote service.
> MCP-Transcribe server allows LLMs to interact with the text content of audio/video files

- README.md
**MCP Prompt Engine Server**
- **Category**: 🛠️ Developer Tools
- **Description**: MCP server for managing and serving dynamic prompt templates using elegant and powerful text template engine. Create reusable, logic-driven prompts with variables, partials, and conditionals that can be served to any [compatible MCP client](https://github.com/modelcontextprotocol/modelcontextprotocol/blob/main/docs/clients.mdx) like Claude Code, Claude Desktop, Gemini CLI, VSCode with Copilot, etc.
- **URL**: https://github.com/vasayxtx/mcp-prompt-engine
> Add MCP Prompt Engine Server

- README.md
- Adds WiseVision MCP server ros 2 note 
- List available topics
- List available services
- Call service
- Subscribe topic to get messages
- Publish message on topic
- Echo message on topic
- Get fields from message type 
- Auto select QoS and message type
> Add WiseVision MCP ROS 2 server

- README.md
- **Description**: A production-grade MCP server for Pix payments in Brazil. Allows agents and apps to generate Pix charges programmatically using multiple fallback providers (Efí, Cielo, and others).
- **URL**: [https://pixmcp.com](https://pixmcp.com)
- **NPM**: [pix-mcp](https://www.npmjs.com/package/pix-mcp)
- **GitHub**: [Regenerating-World/pix-mcp](https://github.com/Regenerating-World/pix-mcp)
- **Features**:
- Generate Pix QR codes and `copy-paste` strings
- Multi-provider fallback logic
- Windsurf-ready
- Open-source and extensible
> feat: add Pix MCP

- README.md
**Description:**
Introduce Beelzebub, an MCP‑based honeypot framework that enables creating decoy tools to detect prompt injection and malicious agent behavior.
**Motivation:**
Strengthen the security of LLM workflows by adding a non‑intrusive detection mechanism.
**Approach:**
1. Provide the agent with tools that are not needed for its ordinary work.
2. Any attempt to use them is tracked and treated as a sign of compromise.
> Feat: Add Beelzebub MCP honeypot

- README.md
- Added Context Apps MCP server to the Workplace & Productivity section
- This MCP server provides an AI-powered productivity suite that connects Todo, Idea, Journal, and Timer apps with
Claude
- Repository: https://github.com/tubasasakunn/context-apps-mcp
- Category: Workplace & Productivity
- Platform support: Cross-platform (macOS, Windows, Linux)
- Implementation: TypeScript, Local service
> Add Context Apps MCP to Workplace & Productivity section

- README.md
It's TypeScript/React chat UI for interacting with agents and MCP tools via WebSocket. This project is not just a Chat UI — it is a boilerplate for building Model Context Protocol (MCP) servers and easily testing their capabilities by chatting with them. The architecture enables rapid development, extension, and interactive experimentation with MCP agents and tools.
> Add new developer tool

- README.md
Reverts punkpeye/awesome-mcp-servers#1231
> Revert "Add new developer tool"

- README.md
Add [Pradumnasaraf/aviationstack-mcp](https://github.com/Pradumnasaraf/aviationstack-mcp) server to the list
> feat: add `aviationstack-mcp` server

- README.md
- Add [wyattjoh/imessage-mcp](https://github.com/wyattjoh/imessage-mcp) to Communication section
- MCP server for reading iMessage data from macOS
- Provides secure access to local iMessage database
> Add imessage-mcp to Communication section

- README.md
Add pi22by7/In-Memoria - persistent intelligence infrastructure for agentic development that gives AI coding assistants cumulative memory and pattern learning. Features hybrid TypeScript/Rust implementation with local-first storage using SQLite + SurrealDB for semantic analysis and incremental codebase understanding.
Added to 🧠 Knowledge & Memory section in alphabetical order by GitHub username.
> Add In Memoria to Knowledge & Memory section

- README.md
Mcp server helps coding agents lookup local codebase functions and prototypes.
Supports local codebase indexing via `universal-ctags` for most popular programming languages.
Especially good for large local codebases that don't fit into agent's context. Besides, doesn't pollute agent's context
> Added function lookup mcp server

- README.md
Teamwork.com official MCP server to manage all main types.
> Add Teamwork.com
